### ISSUE TITLE
headline listing failing for categories

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#1]
(I guess we can just start to file issues against 101wiki even if it still about the "old 101wiki" implementation.)

Please have a look here:

http://101companies.org/index.php/Category:Datalog_theme

I created most of this theme last night.
No headlines get listed.
Perhaps this means that the corresponding module is broken.

**Comment by tschmorleiz** [comment]
I see headlines in the "Classification", perhaps the module recently kicked in. Is this solved?

**Comment by rlaemmel** [comment]
You are right. I probably expected that the worker gets around more than once per day.
