### ISSUE TITLE
link markup on new wiki not fully supported

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#100]
Please have a look here:

http://101companies.org/wiki/Information:Contact

The twitter link with text confuses the markup engine.

The mailto link is not rendered.

For comparison, see how mediawiki does this:

http://mediawiki.101companies.org/wiki/Information:Contact

**Comment by rlaemmel** [comment]
Another affected page:
http://101companies.org/wiki/Course:Web_programming%20for%20Debeka

**Comment by avaranovich** [comment]
Generic links are fixed, for the mailto link, assigning myself a more specific issue #101.
Closing this one.
