### ISSUE TITLE
New property

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#103]
Please add this property:

partOf | Type:Page

(I cannot add. See #102)

**Comment by avaranovich** [comment]
Done. Will look into the issue why you cannot edit.

**Comment by rlaemmel** [comment]
partOf does not show in triples returned by service.

Please go here:

http://mediawiki.101companies.org/wiki/Script:Introduction_to_functional_programming

Check out metadata; it contains this bit:

<pre>
* [[partOf::Course:Lambdas in Koblenz]]
</pre>

But that property does not get rendered.

@tschmorleiz and me already added the actual property page, which was missing:

http://101companies.org/wiki/Property:PartOf

Do you need to re-run some SMW stuff to actually make sure that the new property is taken seriously by the system?

**Comment by avaranovich** [comment]
One need to go to http://mediawiki.101companies.org/wiki/Special:SMWAdmin
and click the button in "Data repair and upgrade" section.

**Comment by rlaemmel** [comment]
Added this sort of information to this page:

http://101companies.org/wiki/Namespace:Property

So the process for adding properties should be clear now (even to myself :-))
