### ISSUE TITLE
Compress metadata/links

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#105]
Look at this page, for example:

http://101companies.org/wiki

There is too much stuff there. It's overwhelming.

Please invent a scheme of folding metadata/links.

Please get in touch to discuss this, if necessary. This is not to so obvious how to do it.

**Comment by avaranovich** [comment]
What if the metadata links are rendered "as a sentence"? One followed by another. (with some space) Would take just multiple lines.

**Comment by tschmorleiz** [comment]
Nice idea, implemented.

**Comment by rlaemmel** [comment]
Yes, better @tschmorleiz and @avaranovich but we need to push for more visual scalability.

Please look at this:

http://101companies.org/wiki/Feature:Cut

The block with the links still fills a screen.

Worse than that, the metadata stuff is super-long.

Any ideas of how to do this?

Some hovering may work.

We would want to apply then I guess some threshold as to when we start to apply the hovering trick.

Anyway, I don't think that this is super high priority.

**Comment by rlaemmel** [comment]
Ok @tschmorleiz and me discussed this.

The plan is sort of this:

We apply a threshold for the number of metadata entries. Let's see we show like 12 entries and when there is more, then there is the "..." button to unfold the rest, very similar to what gmail and other programs do.

We also apply a threshold for the number of links (backlinks). Let's say we show like 20 links and when there is more, then again there is the "..." button.

**Comment by tschmorleiz** [comment]
Applied some collapsing once the thresholds are exceeded.

**Comment by rlaemmel** [comment]
Very nice!
