### ISSUE TITLE
urgent: links broken again

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#106]
@avaranovich , @tschmorleiz how do we get this sorted out?
Any sort of regression testing perhaps that makes sense :-)

Please go here:
http://101companies.org/
None of the links works.

**Comment by avaranovich** [comment]
Do you mean links on the landing page? I don't see them being created https://github.com/101companies/101rails/blob/master/app/views/layouts/landing.html.erb
Let me fix that.

**Comment by rlaemmel** [comment]
Is it intended that those links open a new tab? I don't mind, if there is a good reason for that. It's not what I would expect.
