### ISSUE TITLE
metadata occasionally missing

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#107]
As of now, this page shows no metadata:

http://101companies.org/wiki/Course:Programming%20in_Koblenz

"Edit page" reveals that there is of course metadata.

The only thing I can think of is that this page has a more complicated name.

**Comment by rlaemmel** [comment]
Also missing here:

http://101companies.org/wiki/Course:Lambdas%20in_Koblenz

(BTW, I ran clean-cache recently, but I don't know whether the metadata was there before.)

**Comment by avaranovich** [comment]
@tschmorleiz you need to consider the fact that we support space in URLs (which are escaped by default), and mediawiki replaces all spaces with underscores. I guess this is the reason why the metadata is sometimes missing, because you don't handle this fact properly.

**Comment by rlaemmel** [comment]
Yes, this also occurred to me while cycling. The metadata happens to be missing on multi-word page names.

**Comment by tschmorleiz** [comment]
@avaranovich The request URL for triples is http://triples.101companies.org/org.softlang.semanticendpoint/doQuery?method=getResourceTriples&resource=Course-3ALambdas_in_Koblenz I don't care about URL's of the page. I care about the title, that is given by the backbone model instance. Where do I not handle the URLs not properly?

**Comment by avaranovich** [comment]
Look at the issue details. You show the correct request, but which request do you have for this page http://101companies.org/wiki/Course:Lambdas%20in_Koblenz ? With "space", not "underscore". 
Obviously this one would not work http://triples.101companies.org/org.softlang.semanticendpoint/doQuery?method=getResourceTriples&resource=Course-3ALambdas%20in_Koblenz

**Comment by tschmorleiz** [comment]
http://triples.101companies.org/org.softlang.semanticendpoint/doQuery?method=getResourceTriples&resource=Course-3AProgramming_in_Koblenz Same encoding.

**Comment by avaranovich** [comment]
Just wondering how do you get those underscores (Course-3AProgramming_in_Koblenz), because the page URL is http://101companies.org/wiki/Course:Programming%20in_Koblenz.  How do you get Course-3AProgramming_in_Koblenz  from the page Programming%20in_Koblenz ?

**Comment by tschmorleiz** [comment]
As I said, I don't care about the URL. I only care about page.title of the model. Then I escape that one by replacing blanks by underscore.

**Comment by avaranovich** [comment]
And the title comes from the URL, obviously. But you encode stuff anyhow, that was my concern.

**Comment by tschmorleiz** [comment]
Yeah, I am not sure, I guess we should do this sort of normalization on the server side.

**Comment by avaranovich** [comment]
I just opened the page
http://101companies.org/wiki/Course:Lambdas%20in%20Koblenz
and looked in the Chrome inspector

Request URL:http://triples.101companies.org/org.softlang.semanticendpoint/doQuery?method=getResourceTriples&resource=Course-3ALambdas_in%20Koblenz&callback=callback&_=1366316262397
Request Method:GET
Status Code:200 OK

The URL is _wrong_ for some encoding reason.

**Comment by rlaemmel** [comment]
I would like to suggest that URLs should generally prefer "_" if this is possible as it looks much better on the eye when you copy around URLs. The conversion of " " to escaped space happens somewhere.

**Comment by tschmorleiz** [comment]
Ups, forgot to make the regex greedy. Can we close this now? I guess so.
