### ISSUE TITLE
Rendering of all the links, etc. needs to be straightened up

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#112]
Let's look at this for example:

http://101companies.org/wiki/Visitor%20pattern

Please observe how hard it is to visually comprehend the sections for metadata, links, resources and how the bottom of the page sort of runs into the resources part and that it is not quite clear to what the "hovering" comment applies.

Obviously, there is some taste/personal judgement involved, but we should discuss and make this look easier/clear on the eye. Please let's do this very soon before we get too much frustrated users. @avaranovich should also be involved in the discussion.

**Comment by tschmorleiz** [comment]
I removed indention of section content by request of @avaranovich. Perhaps re-adding this could help.

**Comment by avaranovich** [comment]
What about having a column on the right side of the page with the resources? That would optimize the text on the page.
Generally I don't like the hovering idea, since I have hard time targeting the urls (it often collapses).

**Comment by rlaemmel** [comment]
We really need to discuss that.

**Comment by rlaemmel** [comment]
Closing this as #133 is basically re-iterating the point also using an image.
@tschmorleiz just discussed #133 now and I think Thomas has a plan now.
