### ISSUE TITLE
Deletion of pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#113]
We need a delete/remove feature for 101wiki.

As far as I can see, it is not possible to delete pages.

Just tried to push through some deletion on mediawiki.

There seem to be problems also.

Getting this sort of debug output.

<pre>
array(2) { [0]=> array(7) { [0]=> string(64) "[[identifies::http://www.merriam-webster.com/dictionary/source]]" [1]=> string(48) "http://www.merriam-webster.com/dictionary/source" [2]=> string(4) "http" [3]=> string(1) "p" [4]=> string(44) "://www.merriam-webster.com/dictionary/source" [5]=> string(43) "//www.merriam-webster.com/dictionary/source" [6]=> string(1) "e" } [1]=> array(7) { [0]=> string(35) "[[instanceOf::Namespace:Namespace]]" [1]=> string(19) "Namespace:Namespace" [2]=> string(9) "Namespace" [3]=> string(1) "e" [4]=> string(10) ":Namespace" [5]=> string(9) "Namespace" [6]=> string(1) "e" } } http://www.merriam-webster.com/dictionary/source namespace:namespace namespace:namespace does exist...
</pre>

**Comment by rlaemmel** [comment]
Despite the error message, the page is gone.

It is not gone though on the new wiki.

Running @avaranovich 's cache cleaning script, but trust me we need to make this MUCH smoother.

**Comment by tschmorleiz** [comment]
@avaranovich Can you place add support for the following HTTP request?

URL: http://localhost:3000/api/pages/title
Method: DELETE

Should delete the page with the given title.

**Comment by avaranovich** [comment]
@burgua please provide as requested.
