### ISSUE TITLE
linksTo not working

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#114]
Please check out here:

http://101companies.org/wiki/Resource:Handbook%20of_data_structures_and_applications

It has this sort of link:

<pre>
* [[identifies::http://www.e-reading-lib.org/bookreader.php/138822/Mehta_-_Handbook_of_Data_Structures_and_Applications.pdf ]]
</pre>

Nowhere rendered though.

**Comment by tschmorleiz** [comment]
Fixed.
