### ISSUE TITLE
incomplete support for syntaxhighlight lang codes

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#115]
http://101companies.org/wiki/Feature:Cut

It reports:

<pre>
unknown lang 'sql'
</pre>

If SQL is not supported, then the code must be shown verbatim nevertheless.

**Comment by rlaemmel** [comment]
Thanks!

**Comment by rlaemmel** [comment]
Btw, pages look pretty on my galaxy note 1.

**Comment by avaranovich** [comment]
Yes, we have a responsive design, which adjusts the layout based on the screen resolution.

**Comment by rlaemmel** [comment]
I had to clean cache to see this working.
This is a bit tricky.
So I guess some of your improvements, when you do them will not go live unless cache is cleaned.
Perhaps cache cleaning should be done upon any deployment?
