### ISSUE TITLE
Out of sync due to URL "rewriting"

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#116]
This relates to #91 

@tschmorleiz and @avaranovich please have a look.

There seem to be two pages:

http://101companies.org/wiki/Course:Lambdas_in%20Koblenz

http://101companies.org/wiki/Course:Lambdas%20in_Koblenz

The second one looks good.

When I prefix the first one (i.e., the bad one) with "mediakwiki." then I come to this page:

http://mediawiki.101companies.org/wiki/Course:Lambdas_in_Koblenz

This is also Ok.

If I remove again "mediawiki." then I come to this page:

http://101companies.org/wiki/Course:Lambdas_in_Koblenz

... whose URL is yet different; the content looks good.

Ok, there is some serious URL rewriting s**t going on.

In addition, the old (bad) page seems to exist somewhere but it cannot be retrieved/deleted with mediawiki as far as I can tell.

**Comment by rlaemmel** [comment]
There is something fishy going on with "_" versus " ".

For instance see how the page name is rendered: http://101companies.org/wiki/Course:Lambdas_in_Koblenz

<pre>
Course:Lambdas in_Koblenz
</pre>

**Comment by avaranovich** [comment]
Do I understand correctly, that the "reference" name of the page is "Course: Lambdas in Koblenz"? Which is represented as http://mediawiki.101companies.org/wiki/Course:Lambdas_in_Koblenz in mediawiki, where spaces are automatically always changed to an underscore.

**Comment by avaranovich** [comment]
Please pull 101rails project to get an updated script for cache cleaning. The content is now in sync.
