### ISSUE TITLE
[[ ... | ... ]] markup not rendered correctly

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#117]
Please go here:

http://101companies.org/wiki/Course:Lambdas_in_Koblenz

There is some markup like this:

<pre>
* Lecture [[Script:Introduction_to_functional_programming|Introduction]]
</pre>

It is rendered like this:

<pre>
Lecture Script:Introduction_to_functional_programming
</pre>

... where it should be rendered like this:

<pre>
Lecture Introduction
</pre>

**Comment by tschmorleiz** [comment]
These links are rendered using the client-sided parser. Therefore reassigned to Andrei.

**Comment by rlaemmel** [comment]
Wonderful
