### ISSUE TITLE
LinkedData-like URI-resolver

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#12]
Currently, we leverage the URI scheme provided by MediaWiki/SMW.

In particular, we host all resources in .../resources/...

With LinkedData in mind, we may want to also provide more standardized, less idiosyncratic URIs like this:
- 101companies.org/language/Java
- 101companies.org/technology/JUnit
- 101companies.org/feature/Type-driven_query
- 101companies.org/concept/Model_view_controller
- 101companies.org/contributor/Thomas_Schmorleiz
- 101companies.org/contribution/syb

Thus, we would need a resolver.

Before we do this, we should look more into LinkedData best practices.

**Comment by rlaemmel** [comment]
It looks like this is a leftover from the times prior to the Discovery Service.

**Comment by rlaemmel** [comment]
@martinleinberger , agreed?

**Comment by martinleinberger** [comment]
No complains from my side.
