### ISSUE TITLE
Default injections into namespaces

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#124]
@avaranovich and @tschmorleiz we need to discuss this.

I guess we might want to auto-add instanceof properties for all save ops relative to the namespace of the saved page.

This will improve discoverability but stress scalability of metadata rendering.

**Comment by rlaemmel** [comment]
This is not super high prio.

**Comment by tschmorleiz** [comment]
This works, no? Please close if so

**Comment by rlaemmel** [comment]
Yup, great.
