### ISSUE TITLE
No underscores in render page names

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#125]
http://101companies.org/wiki/Script:Introduction_to_functional_programming

Please note: this is about the rendering on the page; NOT how the URL looks like.

Currently:

<pre>
Script:Introduction to_functional_programming
</pre>

Wanted:

<pre>
Script:Introduction to functional programming
</pre>

**Comment by tschmorleiz** [comment]
Fixed.

**Comment by rlaemmel** [comment]
See here:

http://101companies.org/wiki/Function%20composition

This link has been generated by markup "[[Function composition]]" on this page:

http://101companies.org/wiki/Script:Introduction_to_functional_programming

So the space escaping is still around.

Do we want those "%20"?

**Comment by tschmorleiz** [comment]
Reassigning to Andrei, since this is a server-sided parsing/rendering issue.
