### ISSUE TITLE
Non-responsive save button

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#127]
It happens to me quite often that "save" takes more than just a fraction of a second but there is nothing to tell me that the system is actually doing something. Some sort of idle or recoloring would help.

I also have the feeling that sometimes clicks of the "save" button get lost; will keep an eye on this.

**Comment by rlaemmel** [comment]
Just confirming, "save" does not cause any response in the UI. When things are fast, that's not a problem. Often, saving takes 1-4 seconds and then it is strange when there is no response (coloring etc.) whatsoever.

**Comment by tschmorleiz** [comment]
Added some feedback (small spinner) indicating that saving is happening.
