### ISSUE TITLE
fragment markup not processed properly upon page save

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#128]
I think the following mis-behavior appears to be pretty reproducible.
1. You edit a page to add some "fragment" markup.
2. You save the page but you get this error message where the source code should be:
   <pre>
   undefined method `[]' for nil:NilClass
   </pre>
3. You reload and the source gets rendered.

This will be very confusing for users because they are led to believe that "fragment" stuff is not working. Actually, I spent quite some time with trying out fragment markup rewriting because I didn't realize that I was actually doing the right thing and everything would be dandy if I just reload.

**Comment by avaranovich** [comment]
@tschmorleiz can you please create some kind of sequence diagram (or at lest step-by-step textual spec, which services are called from the client in which order when the user edits and saves the page?

**Comment by rlaemmel** [comment]
We could also do a code review. It looks like there is a bunch of issues upon save. Perhaps, this also relates to the issues with the back button and "Something went wrong" messages.
