### ISSUE TITLE
Make fragment markup "discoverable"

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#129]
This is urgent as in "needed for the next FP lecture and needed for the experience of the students".

Let's go here for an example:

http://101companies.org/wiki/Hello_world_program

There is this sort of fragment markup:

```
 <fragment url="HelloWorld.java"/>
```

However the rendered page does not reveal the fragment URL.

It should be shown a bit like a "caption"; I would say in the upper right corner, but anything that you prefer from a usability point of view is fine with me.

The URL should be linked to the corresponding "format=html" URL of the discovery service. In this manner, we will be able to get anywhere. 

Great!
Looking forward this feature.

**Comment by avaranovich** [comment]
Please close the issue if you like how it is done.

**Comment by rlaemmel** [comment]
Yes, nice.
