### ISSUE TITLE
edit etc. buttons not properly position when using longer page names with longer titles

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#130]
Actually, one cannot even click the buttons then.

![hello](https://f.cloud.github.com/assets/1208815/405714/c2bd3712-aa02-11e2-8a7c-52b25e923897.jpg)

I can sort of work around this by making the font smaller thereby creating more space for the page name and the buttons to be in one line.

Easily reproduced by making the font larger.

**Comment by rlaemmel** [comment]
@tschmorleiz had discussed this.

@tschmorleiz can you perhaps win @burgua and @arkadi-schmidt to do it?

The idea would be to stack all horizontally aligned buttons in a drop-down menu (like "Action").

**Comment by tschmorleiz** [comment]
Working on this one.

**Comment by tschmorleiz** [comment]
Fixed.

**Comment by rlaemmel** [comment]
Looks great.

**Comment by burgua** [comment]
maybe hide it at all, if not signed_in?

http://take.ms/rRQ7p

**Comment by tschmorleiz** [comment]
Done, thanks for noticing

**Comment by rlaemmel** [comment]
Thanks @burgua for noticing and thanks @tschmorleiz for fixing.
