### ISSUE TITLE
Some metadata sections are not rendered properly

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#131]
![metadata](https://f.cloud.github.com/assets/1208815/405731/b1b767ba-aa04-11e2-8248-8aef704da0ae.jpg)

http://101companies.org/wiki/Script:Introduction_to_functional_programming

**Comment by rlaemmel** [comment]
Another example follows:

![moremetadata](https://f.cloud.github.com/assets/1208815/405821/4768e1bc-aa14-11e2-9832-5b3f5147010b.jpg)

**Comment by rlaemmel** [comment]
BTW, if you click any of those strangely render metadata entries, this is not working; one does not get to the "object". So navigation is unfortunately broken. Let's rate this another high-prio bug because students will surely struggle with this.

**Comment by rlaemmel** [comment]
Closing this for now as it is currently not re-producible.

**Comment by rlaemmel** [comment]
As discussed over Skype with @tschmorleiz this issue seems to kick in for some sort of out-of-quota reason:

In the JS console I see this stuff:

<pre>
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self' *.disqus.com:* *.google-analytics.com:* *.scorecardresearch.com:*".
 disqus.com:9
Got there. application-d5ac4eecd441ee11b3dc816105e7afe0.js:1
GET http://101companies.org/wiki/theme-chrome.js 500 (Internal Server Error) application-d5ac4eecd441ee11b3dc816105e7afe0.js:1
</pre>

At the same time Disqus seems to stop working:

<pre>
DISQUS seems to be taking longer than usual. Reload?
</pre>

"NOTE: Basic API accounts are restricted to 1,000 requests per hour."
http://disqus.com/api/docs/

So how do we suffice with 1000 requests?

How do we avoid having the page rendering disrupted by this issue?

**Comment by tschmorleiz** [comment]
Disqus is now loaded on demand by user.

**Comment by rlaemmel** [comment]
At this point I can reproduce this when using "mobile data".
Both on the tablet and on a machine connected through tethering.
I will report back once the issue also pops up on the uni network or anywhere else.

**Comment by tschmorleiz** [comment]
Fixed once and for all.
