### ISSUE TITLE
Youtube URLs should probably not be shown as is

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#132]
![squeeze](https://f.cloud.github.com/assets/1208815/405737/11259442-aa05-11e2-95ae-81139c30a092.jpg)

The URL is essentially an ID and showing it in the way currently done looks strange.

**Comment by tschmorleiz** [comment]
For Wikipedia and alike the title of the page is part of the URL. This is not the case for Youtube URLs, I guess we need to extract somehow. Let's discuss.

**Comment by rlaemmel** [comment]
We will show them for now.

Ultimately, we could special-case YouTube and use its API to fetch the video name.

Not urgent anymore as we are using a special link convention for the more important scenarios of YouTube links.

See here for the "Material" section:

http://101companies.org/wiki/Script:Introduction_to_functional_programming

Perhaps @arkadi-schmidt or @burgua could eventually work on this.

In fact, a more general solution to think a bit more about other resources (other than YouTube) and see whether we also would want to prefetch page titles.

**Comment by burgua** [comment]
So, in this way?

http://take.ms/Kppy5

**Comment by rlaemmel** [comment]
@burgua Thanks for this proposal.

@tschmorleiz, @avaranovich, and me discussed this right away.

I am reassigning to you.

Here are the design issues that we came up with --- based on your proposal.

We suggest to add markup like this:

```
 <media url="http://www.youtube.com/watch?v=AWIO3nPInzg">
```

It should be rendered in the way you suggest: title plus clickable preview.

This would work with Youtube for now, but we could overload the "media" support for other sources later.

Can you pull this off?

@tschmorleiz and @avaranovich are ready to help where needed.

**Comment by burgua** [comment]
Sounds ok.
But I will need some support from @tschmorleiz 
I actually don't fully understand, how it's rendered. Better in Skype.

**Comment by burgua** [comment]
Made first version,
could @avaranovich @tschmorleiz look at it?
https://github.com/avaranovich/wikicloth/pull/2/files

**Comment by avaranovich** [comment]
@burgua have a look at the page, http://101companies.org/wiki/Script:Introduction_to_functional_programming
seems it is not handled yet. I did upgrade the parser.

**Comment by burgua** [comment]
@avaranovich ...and you need to merge new pull request https://github.com/avaranovich/wikicloth/pull/3

**Comment by avaranovich** [comment]
Works. :+1:

**Comment by rlaemmel** [comment]
Just wanted to say that this is really great!
