### ISSUE TITLE
Sort of scrambled/squeeze page area at the bottom

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#133]
Look at this:

![squeeze](https://f.cloud.github.com/assets/1208815/405737/11259442-aa05-11e2-95ae-81139c30a092.jpg)

These are very different categories of page content in very little space without clear margins or separators. Perhaps some horizontal lines could help or some other UI improvement.

**Comment by tschmorleiz** [comment]
Did some changed. Please close if this works for you.

**Comment by tschmorleiz** [comment]
Closing for now.

**Comment by rlaemmel** [comment]
Getting closer, but :-)

http://101companies.org/wiki/Script:Introduction_to_functional_programming
1. Why ":" after "Links" and "Resources"? We don't use ":" elsewhere.
2. "Links" section closer to "Metadata" section than generally other distances between other section. More space please (I guess).
3. Having no resources but the header "Resources" looks strange. Perhaps put "None" in italics there.

![img](https://f.cloud.github.com/assets/1208815/418900/ccec28fa-acba-11e2-8144-95bba7db1c71.jpg)

**Comment by tschmorleiz** [comment]
Fixed that.

**Comment by avaranovich** [comment]
I often see an empty "Resources" section. Is that intended?

**Comment by tschmorleiz** [comment]
Can you give an example?

**Comment by avaranovich** [comment]
Yes, the page in this issue  http://101companies.org/wiki/Script:Introduction_to_functional_programming
it is also on the screen of the issue

**Comment by rlaemmel** [comment]
@tschmorleiz did you actually deploy your changes?
Because none of the things I mentioned were actually addressed.
Repeating them here.
1. Why ":" after "Links" and "Resources"? We don't use ":" elsewhere.
2. "Links" section closer to "Metadata" section than generally other distances between other section. More space please (I guess).
3. Having no resources but the header "Resources" looks strange. Perhaps put "None" in italics there.

**Comment by tschmorleiz** [comment]
Redeployed. Please close if Ok.

**Comment by rlaemmel** [comment]
yes, looks good, BUT metadata is again rendered in a strange way; see screenshot.

![img](https://f.cloud.github.com/assets/1208815/422709/e7888074-ad31-11e2-93fe-3f4ab4b2be7b.jpg)

**Comment by rlaemmel** [comment]
Looks good.
