### ISSUE TITLE
Use page name in browser tab caption

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#134]
Currently it says "wiki" everywhere.
It would be better to do something similar to other wikis.
That is ,the short page name of the current page should be used as the tab name.
Such as Feature:Total.
This way one can have several tabs for 101wiki and still now well what tab is what.

**Comment by tschmorleiz** [comment]
Added titles.

**Comment by burgua** [comment]
this changes killed pages http://101companies.org/contributions, http://101companies.org/users

**Comment by tschmorleiz** [comment]
Yep.

**Comment by rlaemmel** [comment]
But it is not very useful the way it is now.
It shows the entire URL 101companies...
This way one cannot see the interesting part like "Contribution:haskellStarter".
Do you agree?

**Comment by rlaemmel** [comment]
Confirming that this still needs to be fixed.

**Comment by tschmorleiz** [comment]
Should be fixed. Please close if you see your issues are resolved.

**Comment by rlaemmel** [comment]
Yes, fixed. Thanks.
