### ISSUE TITLE
Improve top header (with 101companies in strange font)

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#135]
Not sure what we should put there.
We can keep 101companies, perhaps just in a less crazy font.
We could also think more profoundly about a logo :-)

**Comment by burgua** [comment]
Less crazy fonts:

Ubuntu: http://take.ms/UucZe

Rockwell: http://take.ms/nxzuz

Open Sans: http://take.ms/6EJMZs

Lato: http://take.ms/6khEJ

Arvo: http://take.ms/AklKdS

Josefin Slab: http://take.ms/nT4u0

Also made in caps and bigger.

**Comment by rlaemmel** [comment]
I wouldn't mind a more serious font, if @tschmorleiz feels like picking one, but we can as well wait for the proper logo.

**Comment by tschmorleiz** [comment]
Sure the font is crazy, I just picked something playful for now. Picking a serious font now will make the page very "plain". So let's wait for a logo.
