### ISSUE TITLE
identifies/linksTo not discoverable

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#137]
Conceptually, it is a pretty big deal as to whether one uses "identifies" or "linksTo".

In terms of rendering, though, this difference is not highlighted.

Check out this page with both identifies and linksTo:

http://101companies.org/wiki/Function%20composition

We need to clarify that "identifies" is a semantically stronger link than linksTo.

**Comment by tschmorleiz** [comment]
I added predicate information to the links.

**Comment by rlaemmel** [comment]
Pretty cool!
