### ISSUE TITLE
Cache seems to be prone to " " versus "_" difference

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#138]
It looks like caching is too difficult :-(

@tschmorleiz please help @avaranovich to get this issue resolved.

I see different pages depending on whether I use "_" versus escaped " " in URLs.

In fact, I don't have much control over what is used because these different options are encountered by links on pages.

The escaped " " version kicks in every now and then. It looks like this shows the old stuff.

Sorry if I cannot be more clear, but this seems to be an ugly issue.

So let's discuss on Monday.

**Comment by rlaemmel** [comment]
Just some data points.

So we start here:

http://101companies.org/wiki/Script:Introduction_to_functional_programming

Then we click "function composition" and hence, get here:

http://101companies.org/wiki/Function%20composition

Should this be better "_" instead of "%20"?

Anyway, I would see different content for some pages, depending on whether "_" or "%20" was used.

**Comment by rlaemmel** [comment]
Well, look at the link from 

http://101companies.org/wiki/Script:Introduction_to_functional_programming

to

http://101companies.org/wiki/Script:Introduction_to%20functional%20programming

So this link prefers "%20".

However, this page is out of sync.

What's in sync is the page with a slightly different URL:

http://101companies.org/wiki/Script:Introduction_to_functional_programming

Please sort this out, as it can be hugely confusing.

**Comment by rlaemmel** [comment]
@avaranovich and @tschmorleiz This is a severe problem. I have lost various changes this way and overall I am not sure how I can edit things in any proper way with this feature in place.

**Comment by avaranovich** [comment]
@tschmorleiz  If I go here http://101companies.org/wiki/Script:Introduction_to_functional_programming there is a link in a "Links" section http://101companies.org/wiki/Course:Lambdas_in%20Koblenz  Why those links are inconsistent? One underscore and one space? The solution is to make sure that all links are with underscores.

**Comment by tschmorleiz** [comment]
The client only uses those links rendered by the server. I don't touch rendered HTML. Therefore I guess the server would be the right place to normalize.

**Comment by avaranovich** [comment]
@tschmorleiz which call do you use to get "Links" section? I guess those are backlinks, right? They're indeed rendered in a weird way.

**Comment by tschmorleiz** [comment]
I get these backlinks (as an array) from the server. I can fix this for now on the client. Question is, should we generally normalize all links retrieved by the server?

**Comment by tschmorleiz** [comment]
Fixed this for the Links section that is in control by the client. We still need to fix it for the server-sided rendered HTML. For instance "Functional composition" here http://101companies.org/wiki/Script:Introduction_to_functional_programming

**Comment by avaranovich** [comment]
I did 2 things: a) urls with spaces are redirected to underscores (exactly in the same way as mediawiki does). b) spaces in backlinks are replaced with underscores.

**Comment by tschmorleiz** [comment]
In the console in Chrome I get

Wiki.page.get('backlinks')
["Course:Lambdas_in_Koblenz", null]

Can you please remove null from the array that is set on the server?

**Comment by avaranovich** [comment]
@tschmorleiz can you please specify the page on which you get this?

**Comment by tschmorleiz** [comment]
Please go here http://101companies.org/wiki/Script:Introduction_to_functional_programming
