### ISSUE TITLE
How to refer to fragments (files) on 101wiki pages?

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#139]
I was thinking of using this markup:

```
 All the remaining functions are implemented in the same module: <fragment url="src/Main.hs" show="false"/>
```

This text should appear after the detailed explanation of the "total" feature. However, this leads to rendering the actual module, even though I was hoping for "show=false" to work.

Please support fragment links that render the link in some nice way.

**Comment by avaranovich** [comment]
Did you try 

```
<file url="src/Main.hs" /> 
```

**Comment by rlaemmel** [comment]
I now also tried that both with and without show="false".

It leads to strange results such as this (when rendered):

<pre>
All the remaining functions are implemented in the same module:
https://github.com/101companies/101haskell/tree/master/contributions/haskellStarter/src/Main.hs">Main.hs
</pre>

See the end of the illustration section here:

http://101companies.org/wiki/Contribution:haskellStarter

**Comment by avaranovich** [comment]
The issue was actually related to broken links, now it renders the link to the file.
