### ISSUE TITLE
Proper landing page

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#14]
As discussed, we need to design a proper landing page.
We should not rely any longer on mediawiki to host the landing page.
So we need to decide on a website technology to use.
We also need someone to think about a great design for the landing page.
Technology-wise, this must be brain-death simple.
The key challenge is really to get going on a proper page design.

**Comment by avaranovich** [comment]
Reassigned the issue to myself.
Created 2 related issues based on the last meeting:
https://github.com/101companies/101wiki/issues/28
https://github.com/101companies/101wiki/issues/27

**Comment by avaranovich** [comment]
Closing this issue in favor for https://github.com/101companies/101wiki/issues/92
