### ISSUE TITLE
Unstable behavior on cache

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#141]
I see these sorts of things regularly:
- When clicking a link, one gets to the page where the page name is then written in lower case.
- When using the back button, one gets to see a version of the page that is outdated. Reload repairs the problem.

Especially the second one we need to fix this because it takes a good share of the author's concentration not to be fooled by (not to edit) these wrong versions.

**Comment by avaranovich** [comment]
@tschmorleiz I think this is a client-side issue?

**Comment by rlaemmel** [comment]
I haven't seen this in a while. 
So I am closing.
There is the more severe "back button" issue.
