### ISSUE TITLE
Getting all day "DISQUS seems to be taking longer than usual."

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#142]
Does this work for you?
What is the way to debug this behavior.
(Not too urgent.)

**Comment by tschmorleiz** [comment]
Works for me. Let's check tomorrow.

**Comment by rlaemmel** [comment]
It looks like DISQUS is fine with me again.
I keep an eye on this.

**Comment by rlaemmel** [comment]
So this is a quota / API issue. 
Disqus not working for me all the time.
I guess this is because I am using the wiki :-(

**Comment by burgua** [comment]
Or some cronjobs open a lot of pages

**Comment by tschmorleiz** [comment]
This is per user, so not related to cron jobs. For now I changed it so that Disqus is loaded on demand.

**Comment by burgua** [comment]
nice
