### ISSUE TITLE
No space escapes but only "_" in URLs

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#144]
I think this is mentioned here and there, but a designated issue may not hurt.

Here is how you can reproduce it.

http://101companies.org/
Click courses: http://101companies.org/wiki/Namespace:Course
Clcik the FP course: http://101companies.org/wiki/Course:Lambdas%20in_Koblenz

Ooops, there we go there is this "%20" stuff.

Click the first lecture of the course: http://101companies.org/wiki/Script:Introduction%20to%20functional%20programming

Ooops, there is again some URL with escaped spaces:
http://101companies.org/wiki/Script:Introduction%20to%20functional%20programming

**Comment by avaranovich** [comment]
Related https://github.com/101companies/101wiki/issues/138
