### ISSUE TITLE
Sections get merged

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#145]
It looks like it is easy to end up merging sections accidentally.
My hypothesis is that if one has not an EOL in the last line of a section (when doing section-level edit) that the section may get merged with the next one.

So I just ended up getting this; see "Relationships":

<pre>
All the remaining functions are implemented in the same module: <fragment url="src/Main.hs" show="false"/>== Relationships ==

In the interest of maintaining a very simple simple beginner's
</pre>

**Comment by tschmorleiz** [comment]
@avaranovich, I guess we should add some new line when joining sections when updating.

**Comment by avaranovich** [comment]
@rlaemmel The issue should be fixed, can you tell us on which page do you have it, and do you still have it?
