### ISSUE TITLE
Sort of preview/pdf symbol for .pdf links?

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#150]
I really like the new media tag for youtube videos.

Could this be modestly extended to also do something simple for .pdf links.

See, for example, the "Material" section on this page:

http://101companies.org/wiki/Script:The_Expression_Problem

What would be a good thing to do here?

Perhaps some sort of standard PDF icon with some title that could be attached by the media tag?

https://www.google.de/search?q=pdf&rlz=1C5CHFA_enNL504NL504&source=lnms&tbm=isch&sa=X&ei=bqF3UeHIIsXMtQaVpYGgAg&ved=0CAoQ_AUoAQ&biw=1097&bih=604

So currently the link looks like this:

```
 [http://userpages.uni-koblenz.de/~laemmel/pttcourse/slides/xproblem.pdf]
```

Perhaps, it could look instead like this:

```
 <media url="http://userpages.uni-koblenz.de/~laemmel/pttcourse/slides/xproblem.pdf" name="Slides" />
```

Does this make sense?

**Comment by rlaemmel** [comment]
@tschmorleiz @avaranovich I would also want to know whether you think this is a sound idea.

**Comment by martinleinberger** [comment]
I'm not sure if this is a good idea, because of the work it would create, but the Confluence Wiki has a really cool feature - it can display .pdf documents:
![confluence_pdf](https://f.cloud.github.com/assets/1643263/419129/ed8b38aa-acc2-11e2-946a-965699bd8173.png)

I think there are libraries for this (quick search revealed [a Mozilla project, for example](https://github.com/mozilla/pdf.js)), but I guess even then it takes quite some work to get this running.

**Comment by avaranovich** [comment]
We could also have a PDF preview, there is an implementation is javascript https://github.com/mozilla/pdf.js/
here is the running example http://jsbin.com/pdfjs-helloworld-v2/1/edit and here http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by rlaemmel** [comment]
I think the most we should do is preview of a cheap kind (typically first slide). 
Initially, just a PDF icon would do.
The pdf preview, if any, should be completely client-side.
It should not be too costly in terms of data pulled for the preview.
Just some thoughts.

**Comment by burgua** [comment]
Of course, we can just add pdf-icon.

Some possible ways to go, if you want some slider for pdf-s:
- upload to some external services as [**Scribd**](http://de.scribd.com), [**Slideshare**](https://de.slideshare.net) or (I forgot the third)
- retrieve iframe with rendered pdf
- embed in page

And pretty **simple** looks [**Google Doc Viewer**](https://docs.google.com/viewer). Just write an iframe without uploading -> and evil Google will upload file and prepare all for you.

Example:
![5177bb8be4b0484a551c037c](https://f.cloud.github.com/assets/123756/419451/6cd467e8-acce-11e2-89c5-7949650f0b70.png)
https://docs.google.com/viewer?url=http://userpages.uni-koblenz.de/~laemmel/pttcourse/slides/xproblem.pdf

**Comment by burgua** [comment]
So, your thoughts?

**Comment by rlaemmel** [comment]
If you are in the building, please say hello.

I am not sure that I know enough to favor strongly any of your great proposals.

I am not 100% sure that I would want to share slides via external services, but perhaps this is the way to go, as I am not constraining access anyhow. So if you prefer this, let's go that way. The Google Doc Viewer seems to lead to a nice preview also and it does seem to work with arbitrary domains.

I have uploaded a deck to slideshare:

http://www.slideshare.net/rlaemmel/patterns-19905697

This is for this lecture:

http://101companies.org/wiki/Script:Selected_design_patterns

Perhaps slideshare is just cool.

**Comment by burgua** [comment]
If you would like to use Google Doc Viewer - it's possible to do it today.

You can write smth like 

```
<media url="full_path_to_pdf.pdf" name="slide_names">
```

And it will be rendered without any hard work with backend.
Other approaches need more time to implement.

Today I'm in building till 11:30 and since 13:30, so if it's appropriate - I can say hello.

**Comment by arkadi-schmidt** [comment]
Before merging the code please add slideshare api and secret.

New media tags works so

```
<media url="slideshare_url_to_presentation">
```

**Comment by arkadi-schmidt** [comment]
Please merge this after retrieving slideshare api key/secret https://github.com/avaranovich/wikicloth/pull/4

**Comment by burgua** [comment]
So, looks working now.
Example page: http://101companies.org/wiki/Bar2
Markup for it:

```
<media url="https://de.slideshare.net/rlaemmel/patterns-19905697" />
```

@rlaemmel can we close the issue?

**Comment by rlaemmel** [comment]
This rocks.
I'll play with this some more and then close.
Thanks,
Ralf

**Comment by rlaemmel** [comment]
It just works great.

Just one tiny thing.

Have a look here:

http://101companies.org/wiki/Script:XML_data_binding

When using slides on a white background the actual frame for the deck is not recognizable.

Can you put some frame around the rendered page?

**Comment by rlaemmel** [comment]
Also, I don't think that the name of the slide deck needs to be shown at the left upper corner as it is already stated at the left lower corner with additional info (the author). So please remove the redundant mentioning at the left upper corner.

**Comment by rlaemmel** [comment]
Other than that I just very happily converted the existing 3 PTT lectures to slide share and changed the markup accordingly.  All great.

http://101companies.org/wiki/Course:Programming_in_Koblenz

**Comment by burgua** [comment]
Removed duplicated title.

> deck is not recognizable

In progress

**Comment by burgua** [comment]
So, here we have flash-obejct with very strange markup. 

It has inside itself on the right side and bottom some white line (2px width). 
Any borders looks weird, outlines are hidden by element itself, changing background is also weird.

So @rlaemmel, here we will need help of someone, who is good in frontend, e.g. @tschmorleiz 

The best we found was:

![51877463e4b0484a551fac4c](https://f.cloud.github.com/assets/123756/465339/1719765e-b62e-11e2-8cd4-b9bfe1239294.png)

**Comment by rlaemmel** [comment]
It's apparently to hard to fix.
So I am unassigning until someone comes along to fix it.

**Comment by burgua** [comment]
Implemented by slideshare itself
http://take.ms/5MQvj
