### ISSUE TITLE
Back button not returning to edited page

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#154]
Reproduce like this:
- Edit some page (and save).
- Click a link.
- Use back button to go back to edited page.
- Observe that page looks as prior to editing.
- Reload: correct page is shown.

This probably means that the client does not handle the back button correctly.

**Comment by rlaemmel** [comment]
This would be nice to be fixed as I tend to loose changes this way.

**Comment by tschmorleiz** [comment]
Discussed this with Andrei since this requires both server- and client-sided changes. Should be fixed soon.

**Comment by tschmorleiz** [comment]
As discussed, we changed the way to load pages:
Now, the the actual content of the page (wikitext source/parsed) is fetched **on the client asynchronously once the DOM is ready**. 
This results in the effect that when using the back button the browser does not show the outdated content, but rather Javascript fetches again, thus getting the current content. 
This is also more "Backbone idiomatic".

**Comment by rlaemmel** [comment]
Wow
