### ISSUE TITLE
slideshare account for 101companies

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#155]
@avaranovich I am happy to create the account, but please also go ahead, if you like.

We should connect the account with 101companies@gmail.com.

The name of the user is Joe Hackathon.

**Comment by rlaemmel** [comment]
@arkadi-schmidt @burgua We create such a slideshare account for 101companies and plan to upload things typically to that account (rather than to personal accounts like mine). Would it be easy to also reference slideshares of other accounts on 101wiki, if the need ever arises? Well, we can discuss next week. Having support for the designated 101companies account is probably all that's really needed.

**Comment by burgua** [comment]
Using slideshare api you can reference any public "slideshare".

2013/4/27 Ralf Lämmel notifications@github.com

**Comment by burgua** [comment]
So, yes =)

**Comment by avaranovich** [comment]
@burgua Check your mailbok -- the key is there.
