### ISSUE TITLE
mediawiki not operational

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#158]
Cannot get to this page:

http://mediawiki.101companies.org/wiki/Feature:Timeline

(Wanted to use mediawiki to remove the page, in fact, rename it.)

**Comment by rlaemmel** [comment]
Getting this on pages other than mediawiki.101companies.org/wiki

<pre>
Server error
The website encountered an error while retrieving http://mediawiki.101companies.org/wiki/Namespace:Feature. It may be down for maintenance or configured incorrectly.
Here are some suggestions:
Reload this webpage later.
HTTP Error 500 (Internal Server Error): An unexpected condition was encountered while the server was attempting to fulfill the request.
</pre>

**Comment by avaranovich** [comment]
there is an extension by @tschmorleiz which depends on "http://black42.uni-koblenz.de/production/101worker/catTree.xml" which is not available after the death of the worker. Only "namespace" pages are affected. @tschmorleiz is looking into the issue.

**Comment by tschmorleiz** [comment]
Fixed.
