### ISSUE TITLE
When reloading a page with a youtube video the youtube video name does not get upload

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#160]
So I first added markup for a youtube video to a page (and saved).
Then I went to youtube and changed the video's name.
Reloading the page would still show the old title.
This is probably because it gets stored in the cache.
So when I reset the 101wiki cache, then the new name would appear.

Not a big deals, but perhaps a nice scenario to review in the view of our "complicated" (?) cache scheme.

**Comment by burgua** [comment]
Hm, we are retrieving video title every time on every page reload. So, it looks like server-cache of 101Rails.

Do you mean under "101wiki cache" the browser-cache?

**Comment by burgua** [comment]
No actual since May
