### ISSUE TITLE
Embedding .png .jpegs alike into 101wiki pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#162]
@burgua and @arkadi-schmidt , can you please propose some approach for embedding images into 101wiki pages?

I wonder where to conveniently put the images?
Also, what markup to use?
Mediawiki has clearly a story on this, but we need to figure out what we should do on the new 101wiki.

Perhaps you can do some basic analysis and also involve @avaranovich and @tschmorleiz at some point.

Thanks!

**Comment by rlaemmel** [comment]
It just happens that I was working on 101system feature that generates charts and hence if there if there is some simple and nice protocol to upload  and link images that would be cool. I guess we could store images in github and link them the wiki pages perhaps just re-enabling the mediawiki markup. Images should be previewed effectively.

**Comment by rlaemmel** [comment]
github has very severe limitations though on the size of files, but perhaps that mainly applies to showing the file in "raw" mode in the github browser, but we may also cause quota issues when 101 students open a page with a few images at github. So it may be good to discuss whether another solution exists.

**Comment by avaranovich** [comment]
What if we just follow the mediawiki markup, which is already supported by our parser? 
The basic way to include file is [[File:example.jpg|caption]]
http://www.mediawiki.org/wiki/Help:Images

**Comment by burgua** [comment]
I also like this idea about using parser.

**Comment by burgua** [comment]
@tschmorleiz tested it.
It works.

e.g.:

http://101companies.org/wiki/Monad
![5194ca40e4b0484a5522c6cc](https://f.cloud.github.com/assets/123756/512280/613e0124-be20-11e2-9618-1959455919e1.png)

**Comment by rlaemmel** [comment]
Tested it, too.
http://101companies.org/wiki/Contribution:haskellBarchart
And it works wonderfully.
Let's keep the monadic cat until someone complains. :-)

**Comment by burgua** [comment]
If someone will complain, I will **persuade** him.
