### ISSUE TITLE
Screw up of rendering and missing content

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#163]
Somehow the "Contributions" section is no longer recognized as a section.

Also note that there is no edit button for metadata.

Further note that metadata is not rendered properly.

Further, "Contributions" and "Metadata" are missing when I "Edit page" even though they remain visible when reloading the page.

I went to mediawiki and I see this content:

<pre>
== Contributions

* [[Contribution:dom]]
* [[Contribution:jaxbComposition]]
* [[Contribution:jaxbChoice]]
* [[Contribution:jaxbExtension]]
* [[Contribution:jaxbSubstitution]]

== Metadata ==

* [[instanceOf::Course:Programming in Koblenz]]
</pre>

I guess this means that I might have made a syntax mistake perhaps in that I forgot to close "Contributions" with "==". Anyway, such syntax errors should have less epic consequences (such as missing content upon editing.)

![bug](https://f.cloud.github.com/assets/1208815/442970/83986f4e-b16d-11e2-995b-5f5483204ca2.jpg)

**Comment by rlaemmel** [comment]
So I guess missing Edit buttons and lack of recognizing Metadata section as such may be Ok, if the parser error disrupts section structure, but please do not omit content.

**Comment by tschmorleiz** [comment]
Please provide the name of the page.

**Comment by rlaemmel** [comment]
No point in providing that name, as I had to go ahead and fix the page.
However, the issue text above contains the offending page content verbatim.

**Comment by tschmorleiz** [comment]
Problem was that the client was not aware of any sections due to messed up wikitext. Added some fallback: If there are no sections, use the raw content. This allows one to edit such broken pages.
