### ISSUE TITLE
Edit, save not working

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#168]
@arkadi-schmidt and @burgua Can you help?

For example, try editing "Summary" here:

http://101companies.org/wiki/Script:Simple_software_engineering_for_Haskell

Nothing happens upon "Save".

I tried other pages, too.

Also tried "Reload" in all cases.

This is really very urgent, as I need to work on the course for tommororw.

**Comment by tschmorleiz** [comment]
Fixing right now with Andrei and Alex.

**Comment by tschmorleiz** [comment]
Seems this happend due to some merge.

**Comment by tschmorleiz** [comment]
Should be fixed.
