### ISSUE TITLE
Timestamp at the bottom of page not updated past save

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#169]
There are already 1+ issues suggesting that "save" is too limited in how it updates the page. (I remember that metadata is not reloaded / updated upon save.) It looks like that the page really needs to be reloaded asynchronously more or less. Along these lines, I just noticed that the "timestamp + name" at the bottom of the page does not get updated upon save.

Some design review is needed here to decide what really needs to happen per section level save. Redundant re-implementation on the client needs to be avoided, of course. So asynchronous (optimized) reloading is probably needed.

**Comment by tschmorleiz** [comment]
@avaranovich Could you return the new timestamp in the response to a saving request of a page? Then I can update it after section saving.
