### ISSUE TITLE
Lower case links when clicking saved content

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#172]
Try this to reproduce:
- Edit some page
- Create some markup for a link while using lower case.
- Save.
- Click said link.

You will end up on a lower case URL.

If you reload though, then you will end up on an upper case URL.

I think this has to do (like some other issues) with the fact that the client tries to shortcut stuff that would normally be done by the server.

**Comment by tschmorleiz** [comment]
Some links are still lowercase because the fixing relies on #213 to be fixed.
