### ISSUE TITLE
Excessive extra linebreaks between sections

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#175]
In an attempt to fix an earlier bug where sections without in-between linebreaks would get merged, we now face the opposite situation. Linebreaks seem to be added all the time so that sections move appart increasingly.

**Comment by rlaemmel** [comment]
This is urgent as I have already created loads of strange pages that way.

**Comment by rlaemmel** [comment]
Perhaps these extra linebreaks should automagically removed when opening a page for page-level edit?

**Comment by tschmorleiz** [comment]
The problem is that if I remove trailing line breaks on edit, the model is changed without any real changes. I guess we should do this sort of normalization on the server. Will change this on the server beforehand.

**Comment by rlaemmel** [comment]
We should definitely avoid that every "save" adds another line, which is what I think currently happens.

**Comment by tschmorleiz** [comment]
What happens now is that the users only gets sections with removed trailing whitespace. And the server saves sections by joining with a linebreak. So we don't see/store this blowup anymore.

**Comment by rlaemmel** [comment]
Sounds good. Thanks for the quick fix. Overall, we get more features and less bugs. :-) Kudos!
