### ISSUE TITLE
Add "Discover" tab 101wiki pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#179]
@avaranovich perhaps you want to assign this to someone else?

Next to "Wiki" (and "Github" - for some pages), there should also be a "Discover" tab.

This should take one to the discovery service.

Good for round-tripping navigation.

Good for deep integration of the discovery service.

@martinleinberger just mentioning you here so that you know of this request.

**Comment by avaranovich** [comment]
@tschmorleiz Could you please add?

**Comment by tschmorleiz** [comment]
Discussed with @martinleinberger:
Problem is that we have to map Language:Foo to languages/Foo for the URL of the discovery service. We have some mapping code, but don't want to copy it around and make it out of sync. So Martin will add support for URLs such as http://101companies.org/resources?wikititle=Language:Foo&format=html that will then be redirected to the proper URL.

**Comment by rlaemmel** [comment]
Yes, this looks right. Thanks!
