### ISSUE TITLE
edit new pages behaves strangle

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#183]
- Enter the name of a non-existing page.
- Edit the page.
- Observe how "#" appears after the URL.
- Continue editing and say "save".
- Observe how "#" stays in the URL.

I am looking at this URL, for example, past edit:
http://101companies.org/wiki/Context-free_grammar#
The metadata does not get rendered.

**Comment by rlaemmel** [comment]
Back button cycles through the URL with and without "#". 
So it cannot be used anymore.

**Comment by rlaemmel** [comment]
"#" stays even after Cancel.

**Comment by avaranovich** [comment]
@tschmorleiz I am sure you know this already, the metadata often is not rendered because of some "noise" in URL, aka "#" in this issue.

**Comment by rlaemmel** [comment]
I get the feeling that things behave particularly strange when "-" is in the URL.

**Comment by tschmorleiz** [comment]
Should be fixed. Action dropdown has some strange markup, due to this quick fix. Will change later.

**Comment by tschmorleiz** [comment]
Fixed the markup in 101companies/101rails@1362a1bd3a29a82f91f609f63ddd9a1af1b6a6c9
