### ISSUE TITLE
Clicking links with lower case characters gets us occasionally to URLs with also lower case

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#184]
This isn't quite reproducible, but there must be somewhere a code branch that does not turn the link target into upper case. I think this happens specifically after saving. So suppose you do this.

Edit some page and add this sort of markup.

```
 Hallo [[foobar]] Yeah!
```

Save and click "foobar".  You might end up on ..../foobar.

This does not happen all the time.

**Comment by tschmorleiz** [comment]
@avaranovich Could you fix this in the server-sided parsing functionality?

**Comment by rlaemmel** [comment]
@tschmorleiz my impression is that this is a client problem because it seems to happen when clicking links on just saved content

**Comment by tschmorleiz** [comment]
When saving we call a server-sided parsing thingy to get the rendered HTML.
