### ISSUE TITLE
Resource details missing for github URLs

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#185]
Please go here:

http://101companies.org/wiki/Lookahead#

(Not sure about the "#".)

Please hover Resources, github.

The actual repo name is missing; only the final directory name is shown.

**Comment by tschmorleiz** [comment]
"#" is unrelated. What should be the general rule which part to show of the URL?

**Comment by tschmorleiz** [comment]
So, what I currently do is just talking the last element of a split by "/". 

What we could do is the following: Have a map from domain name (say "github.com" or "wikipedia.org") to indicies in the "/" split. The default would be to only show the last part. 

Will implement this idea soon.
