### ISSUE TITLE
Pick a theme for the wiki

### ISSUE THREAD

**Issue by tschmorleiz** [101companies/101wiki#198]
We use Twitter Bootstrap as our front-end UI framework. We do this because
- we are not web designers,
- it provides all reusable components we need, and
- it's responsive.

This is nice, but makes the wiki page look quite vanilla. Therefore I propose to pick a Bootstrap theme. They are really easy to use and integrate. Here are some pages that provide tons of free and paid themes:
- https://wrapbootstrap.com/
- http://bootswatch.com/
- http://themeforest.net/search?utf8=%E2%9C%93&term=bootstrap

The theme should be super-clean. Let's discuss some criteria at the next 101wiki meeting.

**Comment by burgua** [comment]
I love readability theme from boostwatch <3
Am 08.05.2013 22:36 schrieb "Thomas Schmorleiz" <notifications@github.com>:

**Comment by tschmorleiz** [comment]
Yes, very clean. Somewhere I read "The default Twitter Bootstrap theme is the new Comic Sans" :)

**Comment by burgua** [comment]
+1
Sad, but true

**Comment by avaranovich** [comment]
@tschmorleiz @burgua could you create a branch with a new theme? We have a look and decide.

**Comment by burgua** [comment]
It's my development branch with theme spacelab http://bootswatch.com/spacelab/
https://github.com/101companies/101rails/tree/dev
Do'n merge it! Crazy changes inside

**Comment by avaranovich** [comment]
very good, you can show it to us during the next wiki meeting
