### ISSUE TITLE
"Page not found" pops up

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#199]
It looks a new feature is coming along.

When I am hovering over some links, I get "Page not found".

This happens here:

http://101companies.org/wiki/Course:Lambdas_in_Koblenz

Try hovering over the lectures.

This is probably because special markup is used here, right?

**Comment by tschmorleiz** [comment]
Seems like the discovery service does not handle the "Script" namespace properly. Check this:
http://101companies.org/resources/?format=html
Click on e.g. "Concept" and you get all members.
Click on "Script", nothing happens. 
@rlaemmel Could you formulate this better and issue in the appropriate repo?

**Comment by martinleinberger** [comment]
After updating the Mappings, the discovery service has now some members for "Script". I'm not sure why it doesn't work now. Is there another mapping missing? If you have more infos, please let me know...

**Comment by tschmorleiz** [comment]
Thanks for working on this. The page uses this URL (for instance): http://101companies.org/resources?wikititle=Script:Introduction%20to%20functional%20programming%20&format=jsonp
As you see some 500 appears.

**Comment by tschmorleiz** [comment]
There seems to be some trailing "%20", which I will fix. But even if I remove this: http://101companies.org/resources?wikititle=Script:Introduction%20to%20functional%20programming&format=jsonp, still 500.

**Comment by tschmorleiz** [comment]
Actually I get this now for **any** wikititle with ":" in it: http://101companies.org/resources?wikititle=Language:Haskell&format=json. Seem the redirect is broken.

**Comment by martinleinberger** [comment]
It appears as if my latest changes broke something. I'll fix it...

**Comment by martinleinberger** [comment]
Found the bug. The discovery service should be fully functional again. Headlines of scripts are now popping up in the wiki.

**Comment by tschmorleiz** [comment]
Cool! Thanks for helping make this feature work

**Comment by rlaemmel** [comment]
Thanks @martinleinberger and @tschmorleiz .

Looks dandy now.
