### ISSUE TITLE
Process .gitdeps instead of .gitmodules

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#2]
The JavaScript functionality for directing to a repo other than 101companies/101repo need to look at .gitdeps now.

**Comment by tschmorleiz** [comment]
The functionality of the script can now described as follows:
1. it checks if the repo URL can directly be extracted from .gitdeps (e.g. for mongodb). If not:
2. it iterates through all entries with "mode" : "subdirsonly" and for each entry:
   1. requests the corresponding list of subdirs from the GitHub API
   2. checks if any of the subdirs correspond to the contribution at hand and if so uses the URL to this subdir
