### ISSUE TITLE
Headline popup not working in one case

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#200]
http://101companies.org/wiki/Script:Simple_software_engineering_for_Haskell

Hover over "Testing framework".

"Loading headline ..." forever.

**Comment by martinleinberger** [comment]
I assume this is because "Testing framework" does not have a Headline ([wiki](http://101companies.org/wiki/Testing_framework) and [discovery service](http://101companies.org/resources/concepts/Testing_framework?format=html)).

**Comment by rlaemmel** [comment]
Thanks, Martin.
I fixed that.

**Comment by rlaemmel** [comment]
Reopening because I think it should just say that there is no headline rather than loading forever.

**Comment by tschmorleiz** [comment]
Made it more robust: Check "Technology:GWT" here http://101companies.org/wiki/Contribution:gwt for instance.

**Comment by rlaemmel** [comment]
Yes, working now.
