### ISSUE TITLE
Renaming didn't apply

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#201]
I was renaming as follows:

```
 $ python refactor.py rename Script:Simple_software_engineering_for_Haskell Script:Basic_software_engineering_for_Haskell
```

The following reference was not affected:

http://101companies.org/wiki/Course:Lambdas_in_Koblenz

```
 * Lecture [[Script:Basic software engineering for Haskell | Basic software engineering]]
```

**Comment by rlaemmel** [comment]
Looks like this scheme of markup isn't supported.
Just ran into another example like this.

**Comment by tschmorleiz** [comment]
For me all was fine after "make clean-cache". Though I noticed that renaming a page will erase some link titles! Say [NS:Foo|123] becomes just [NS:Bar] when renaming NS:Foo to NS:Bar. That I fixed.

Please check if this work for you now.

**Comment by rlaemmel** [comment]
I shall submit a better/stsble testcase.
