### ISSUE TITLE
Page actions perhaps to be shown as many buttons 

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#204]
With "Rename" coming along the way, we will have even more "page actions".

I believe the reason for putting them into an extra menu was basically "place management".

(The headline was running into the space needed for buttons.)

Perhaps it would be better to use extra space before the headline for all these buttons.

This is sort of "UI" issue. I think it would be better to see all page actions.

We can discuss this.

**Comment by tschmorleiz** [comment]
After discussion on monday, we agreed to show all buttons for now and have a "more" dropdown in case we get more page actions.
