### ISSUE TITLE
Double error message when resource not found

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#205]
Captured the problem on this dedicated page:

http://101companies.org/wiki/Issue:NotFound

See the error message outside the red box.

Sometimes these errors even break the page layout so that page-level edit is not even possible anymore.

Anyway, perhaps these errors can be intercepted more reliably.

**Comment by burgua** [comment]
So it looks now:

http://take.ms/1zGIC

**Comment by rlaemmel** [comment]
Great
