### ISSUE TITLE
Provide help on markup 

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#207]
I guess we need a sort of help button on the wiki so that people can read about the markup they can use.

This page emerges as the page to hold such help:
http://101companies.org/wiki/Information:Markup

Perhaps this page could be linked to some sort of help button; the page would need to open in a new tab of course.

**Comment by tschmorleiz** [comment]
I think we could have to dimensions of support:
- **Syntax insertion:** By highlighting some text and clicking a button the text becomes a headline resp. a link, etc. (this one is rather cheap to have)
- **Syntaxhighlighting and alike:** We use an editor that can be extended in terms of which languages it supports. I will look into options to add wikitext markup and our special markup.

**Comment by tschmorleiz** [comment]
I added some support for syntax highlight of ordinary wiki markup. We can extend the highlighting rules in [this file](https://github.com/101companies/101rails/blob/master/vendor/assets/javascripts/ace/mode-wiki.js).

**Comment by tschmorleiz** [comment]
With the new @-names in place, I guess one thing we should do is auto-rewrite `@suffix` to `101suffix` when editing.

**Comment by tschmorleiz** [comment]
101 -> @ that is.

**Comment by tschmorleiz** [comment]
Please check the editor for the whole page. I implemented the idea of wrapping selected text with markup when hitting a button. Please suggest support for more syntax here.

**Comment by rlaemmel** [comment]
It's already pretty cool, the way it is.
Will be thinking about more.
Great!
