### ISSUE TITLE
Provide more feedback when renaming takes its time

### ISSUE THREAD

**Issue by tschmorleiz** [101companies/101wiki#208]
We do renaming such that all references to the moved page are fixed (see #64). 
This has the drawback that it takes more than just a few seconds for heavily linked pages. 

We show "fixing references..." while the client waits for the response. This indicates that the response could take some time, but I have the feeling we should provide more feedback. I see two options:
- We directly respond when the page is just moved. We therefore need to do the fixing of references in the background. We should therefore show some "Links pending..." on the page while the background task is in progress.
- We provide a progress bar while waiting for the response with some hint like "n/m backlinks fixed".

**Comment by rlaemmel** [comment]
Renaming is sort of an expert feature.
When non-experts use it, then they would probably only rename their own pages that they just created.
Experts will not be surprised to see that this takes time.
I would just do it synchronously and use some widget that shows that something is going on.
The exact progress does not need to be measured.

If we were to do it asynchronously, this could be confusing. For instance, we might continue editing some page pretty much immediately after the uncompleted rename and then loose some changes. This is a nightmare.

So sync and cheap progress visualization, Ok?

**Comment by rlaemmel** [comment]
I think this all looks fine to me.
Closing for now.
