### ISSUE TITLE
Browser needs to go to renamed page

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#210]
Just started renaming and this looks great.

One thing: once renaming is completed, the browser needs to show the new page. Currently, it seems one stays on the old page, which upon reloading is of course gone.

**Comment by tschmorleiz** [comment]
Hm, strange. Just renamed "Function" -> "NewFunction" and I got redirected to the new page once renaming was completed ([code](https://github.com/101companies/101rails/blob/master/app/assets/javascripts/backbone/views/page.js.coffee#L118)). I guess s.th. messed up, such that redirecting was never executed. Did the popup close?

**Comment by rlaemmel** [comment]
Ok, I will do more renaming today and keep an eye on this.

**Comment by rlaemmel** [comment]
I have renamed now a few times and the new page was shown indeed, as expected.

I believe some JS error happened when I did that other rename.

If this ever happens again, I shall try to capture more information and re-open the issue.

**Comment by rlaemmel** [comment]
Ok, I understand what's going on.

Renamed 101companies:Papers to Information:Papers.

I believe the code fails to forward to the new page, whenever the new name has a prefix or perhaps a different prefix.

**Comment by tschmorleiz** [comment]
Should be fixed with https://github.com/101companies/101rails/commit/a3d6505f1a97319c0ba99c8b983724871e2ac403, too.
