### ISSUE TITLE
Some links are not clickable

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#213]
http://101companies.org/wiki/Higher-order_functions_in_Haskell

Hover "Course:Lambdas in Koblenz" in headline.

No proper link seems to be associated with the markup.

Nothing happens when clicking the link.

**Comment by rlaemmel** [comment]
Also go here:

http://101companies.org/wiki/Course:Lambdas_in_Koblenz

Try to click any of the "Script:..." links.

**Comment by tschmorleiz** [comment]
The parsing service returns links like this:
`<a href=\"Script:First steps in Haskell \">First steps</a>`
Which mean, that the `/wiki/` prefix is missing. 

@avaranovich, we discussed this shortly. Therefore I reassign.

**Comment by rlaemmel** [comment]
Just adding that this has worked until yesterday or today. So has something to do with some very recent change.

**Comment by tschmorleiz** [comment]
This also causes the tooltip thingy not to kick in.

**Comment by avaranovich** [comment]
@burgua please check your refactorings concerting this case.

**Comment by tschmorleiz** [comment]
Found the reason by accident when implementing #143 :)
