### ISSUE TITLE
wiki -> 101wiki

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#217]
This is about the name of the page 101companies.org in the browser tab.

**Comment by rlaemmel** [comment]
I think you misunderstood.
I was not referring to the "Wki" tab on a .../wiki page.
I was referring to the "Wiki" title for http://101companies.org/ in the browser.

**Comment by tschmorleiz** [comment]
Like that :question:

**Comment by rlaemmel** [comment]
Like that:

![bug](https://f.cloud.github.com/assets/1208815/523283/b56e4b76-c0a7-11e2-905d-16c6f4b3931c.jpg)
