### ISSUE TITLE
renaming "undefined"

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#218]
Just landed on 

101companies.org/wiki/Undefined

when trying to rename

from Higher-order functions in Haskell

to Script:Higher-order functions in Haskell

**Comment by tschmorleiz** [comment]
Did the rename itself work?

**Comment by rlaemmel** [comment]
Nope

**Comment by tschmorleiz** [comment]
Ok looking into renames with ":".

**Comment by tschmorleiz** [comment]
Did some change and successfully renamed the page you mentioned. Can you please try?
