### ISSUE TITLE
Renaming not finding all occurrences

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#219]
I just renamed "@discoverer" to "@explorer".

Here is some of the markup of the resulting page; see the remaining occurrences of "@discoverer". What's also strange is the first few cars, which looks like as if some chars of the regular text (see "ntegral part") were removed.

<pre>
[[@explorer]]ntegral part of the infrastructure and foundation of the [[@project]]. [[@discoverer]] supports
systematic discovery of all pages on the [[@wiki]], all artifacts in the [[@repo]], and all synthesized data 
available as [[@data]]. To this end, [[@discoverer]] provides access to the various links between all the 
involved resources. In other words, [[@discoverer]] is the Linked Data portal for the [[@project]]. 
[[@discoverer]] is organized as web service (using HTTP GET) with the URL referring to the resource 
and the response containing information about the resource. Different response formats are supported: 
HTML, JSON, and RDF.
</pre>

**Comment by tschmorleiz** [comment]
Should be fixed, tried some pages with multiple occurrences. Please check!

**Comment by rlaemmel** [comment]
Missed all occurrences of 101technology in here:

http://101companies.org/wiki/Technology:HsFragmentLocator

Is that _perhaps_ because of the old name starting with "101"?

**Comment by tschmorleiz** [comment]
So you renamed a page to @technologies? Did you after that fix all references on http://101companies.org/wiki/Technology:HsFragmentLocator manually?

**Comment by rlaemmel** [comment]
Yes, I fixed them manually.
Before I started to do this also reloaded.

**Comment by tschmorleiz** [comment]
I also see correct references on http://101companies.org/wiki/Technology:XmlFragmentLocator for instance. Did you fix _all_ pages?

**Comment by rlaemmel** [comment]
No, I only changed the page that I mentioned.
So then my wild guess is that either this specific page has something very specific :-) or this is a cache problem.
If you don't have any lead here, close it for now and let's hope for the best :-(

**Comment by tschmorleiz** [comment]
Just renamed @technology to 101technology and then back to @technology. Both times all references where fixed (the backlinks listed did not change and I tried some of them to see if **all** occurrences were fixed). Therefore closing for now :)
