### ISSUE TITLE
UI consistency on tabs on 101wiki

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#220]
So we have "action" buttons like "rename" and "delete". That's great. We also have sort of tabs for "101wiki" and "Discover" and some menu for "Code" when looking at a contribution.

The tabs seem to be used to hint at the fact that some other view opens. 

If so, perhaps these names could be cool:
- 101wiki
- 101repo
- 101explorer

I would rather not have a menu for "Code" (which would be now "101repo"). However, I don't know a good name for "Downloading the ZIP" which would blend in well with "101wiki", 101repo", and "101explorer". So perhaps we keep the menu.

Any ideas?

**Comment by tschmorleiz** [comment]
I think we just keep the names in the dropdown menu for 101repo. I think we cannot find any intuitive name for the .zip option. Also, the .zip option does directly correspond to any 101 architecture entity or service.

Changed to "101wiki", "101explorer", and "101repo".
