### ISSUE TITLE
Lower case even after reload

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#221]
I am looking at this page:

http://101companies.org/wiki/@explorer

I am hovering over "fact extractor".

This is the link that I get:

http://101companies.org/wiki/fact%20extractor

Upon clicking it gets rewritten to this link:

http://101companies.org/wiki/Fact_extractor

So this is Ok.

I am just wondering whether we really want these other links to ever surface; again this one here:

http://101companies.org/wiki/fact%20extractor

@avaranovich any comments on this matter?

**Comment by tschmorleiz** [comment]
Same reason as #213. `/wiki/`is missing in href attribute of anchors. Therefore my fixing to upper-case does not kick in. Let's wait for that one to close.
