### ISSUE TITLE
Different fonts for prefix versus basenase

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#222]
I think we had this already; so probably this got rolled back / overridden.

Look here for example (but any page with prefix would work):

http://101companies.org/wiki/Script:Higher-order_functions_in_Haskell

In rendering the title, somehow the prefix should be deemphasized, moved apart further from the basename. I don't remember how it looked like when I liked it, but sort of really the prefix needs to be de-emphasized.

![bug](https://f.cloud.github.com/assets/1208815/538312/33473630-c188-11e2-9dfb-d10f6cb2f950.jpg)

**Comment by tschmorleiz** [comment]
That was easy :)
