### ISSUE TITLE
Layout of landing page sort of taking too much space

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#224]
http://101companies.org/

Unless I make the browser occupy the entire screen and I go to small fonts, I will not see all of the landing page, which I guess is what should be the goal. Do you agree that we should sort of squeeze things a bit more?

**Comment by tschmorleiz** [comment]
Let's discuss on Monday.

**Comment by tschmorleiz** [comment]
@burgua Could you "install" the new bootstrap theme?

**Comment by burgua** [comment]
@tschmorleiz sorry, I dont't have time for this in this week.

**Comment by burgua** [comment]
duplicates https://github.com/101companies/101wiki/issues/254
