### ISSUE TITLE
semantic end point to produce 101explorer-like RDF

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#227]
This is on top of #226.

So let's assume that 101explorer does support format=rdf; @martinleinberger is working on this. (I will file actually another issue on constraints for such RDF, but in the following text, I only assume basics.)

So let's recall what sort of subjects, objects, and predicates are returned by the semantic endpoint:
- subjects and objects: contributions, features, concepts, technologies, languages, ...
- predicates: SMW properties to relate those subjects and objects.

All those subjects, objects, and predicates do have some 101explorer image. That is, we do have 101explorer-based URIs to refer to those guys. So what we should expect is that the semantic endpoint does indeed return URIs for those guys that are **immediately** resolvable with 101explorer, rather than applying any sort of mapping from the endpoint returns to what can be looked up with 101explorer.

In different terms, at the time of writing, the semantic endpoint only returns JSON format where #226 suggest how to standardize that format anyway. Naturally, we also need the semantic endpoint to return RDF and **we do not want to see** the idiosyncratic URIs used by Sesame/SMW; rather we want to see what we are standardizing with 101explorer.

This is technically a bit tricky, but @avaranovich and me discussed that, and I think that @avaranovich has a plan.

**Comment by avaranovich** [comment]
I have been experimenting with handling my own RDF store (sesame) with the schema we need for pages. That approach sounds promising. Basically we can retire semantic wiki completely. This gives us more flexibility in terms of RDF schemas of the page. 

Once this becomes stable, we are one step away from retiring the whole mediawiki. (which means we need to support less services, no mediawiki, no mysql). 

Back to the issue, on Monday I will present my approach.  One of the nice effects of it, that we can easily ask for RDF representation for every page,  we don't even need a semantic endpoint for this. Example http://101companies.org/api/pages/contribution:haskellStarter/rdf    (objects should also be resources, not literals, this is in progress)

Here is the link to my sesame playground
http://triples.101companies.org/openrdf-workbench/repositories/test/export

@martinleinberger FYI.

**Comment by avaranovich** [comment]
ok, here is a reference representation http://101companies.org/api/pages/contribution:haskellStarter/rdf

URIs now conform to those used by 101explorer.
