### ISSUE TITLE
http://101companies.org/wiki perhaps should be expanded?

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#229]
http://101companies.org/wiki is rendered as with the content of http://101companies.org/wiki/@project without though rewriting the URL.
Should the URL be rewritten?
Even when editing the page, the URL remains http://101companies.org/wiki
Is that Ok?

**Comment by avaranovich** [comment]
@burgua please do redirect from  http://101companies.org/wiki to  http://101companies.org/wiki/@project
