### ISSUE TITLE
Deleting page opened in new tab

### ISSUE THREAD

**Issue by burgua** [101companies/101wiki#236]
If page is opened from new tab -> deleting will throw to "new tab" page

https://github.com/101companies/101rails/commit/01a5152051956f597275dbe260d8b101e1dc8695#commitcomment-3289818

http://stackoverflow.com/questions/9564041/why-history-length-is-2-for-the-first-page

**Comment by tschmorleiz** [comment]
Yes, forgot about that +1 thingy.

**Comment by burgua** [comment]
I never knew =)
