### ISSUE TITLE
Page loading is arguably too slow

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#238]
Now that I am editing again for the upcoming lecture, I do notice that the recent resolution of the back button issue has affected perf quite considerably. It takes about 5 seconds to load, for example, http://101companies.org/wiki/Contribution:monoidal

Just guessing, but I think usability is at risk above one sec.

@avaranovich and @tschmorleiz let's discuss what we can do.

**Comment by rlaemmel** [comment]
Basically loading an empty (non-existent) page takes nearly 2 secs.
The full cycle of saving a simple page and seeing everything rendered can easily take 10 seconds.
Texas, we've got a problem.

**Comment by tschmorleiz** [comment]
The red-links feature is partially causing this. Specifically asking the MediaWiki API for the list of all pages. This list is now cached, so you should already see some performance improvements with regards to loading the sections.

**Comment by tschmorleiz** [comment]
The initial request (say before you see the "Loading…" for each section) still takes to much time. We will look into this.

**Comment by burgua** [comment]
By the way, we (I and @arkadi-schmidt ) added support of gzip-compressing and expires-headers for webserver.
After measuring page speed with https://developers.google.com/speed/pagespeed/ before and after we has such results:

**Before:**
Landing page: http://monosnap.com/image/3o7LisCuK1of714RPaZrEJkza
WikiPage: http://monosnap.com/image/WTNvqN78I15QmgrTwPbTrk1SO

**After:**
Landing page: https://developers.google.com/speed/pagespeed/insights#url=101companies.org&mobile=false
WikiPage: https://developers.google.com/speed/pagespeed/insights#url=http_3A_2F_2F101companies.org_2Fwiki&mobile=false

And by the way we blocked **three bad bots from USA, caused 11% of entire requests** to the wiki.
http://whatis.riskyinternet.com/what-is/ip/173.199.115.59/
http://whatis.riskyinternet.com/what-is/ip/173.199.116.19/
http://whatis.riskyinternet.com/what-is/ip/173.199.116.227/

**Comment by rlaemmel** [comment]
Thanks everyone for contributing in many ways.
As we discussed yesterday, the perf is now acceptable.
We want better perf, but this will wait until we retire Mediawiki.
