### ISSUE TITLE
101wiki edit broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#242]
Cannot edit this page anymore:

http://101companies.org/wiki/Course:Programming_in_Koblenz

As soon as I try save it goes into an infinite loop.

Will try other pages also.

**Comment by tschmorleiz** [comment]
Please retry.

**Comment by rlaemmel** [comment]
Yes, save completed fine now (after like 10secs).

**Comment by tschmorleiz** [comment]
Yes, really slow. I managed to identify the problem it it's this line https://github.com/101companies/101rails/blob/master/app/models/page.rb#L174 Here we call the MediaWiki API to actually store the page. So essentially the underlying MediaWiki API takes its time.

**Comment by avaranovich** [comment]
@tschmorleiz, we could fork a new thread just for saving https://github.com/tra/spawnling
