### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#245]
No metadata is rendered on this page:

http://101companies.org/wiki/Metadata

How come?

There should be the auto-instanceOf into Namespace:Concept, right?

Is that because this concept is called "Metadata"?

**Comment by rlaemmel** [comment]
Or is it because I am mentioning the instanceOf::Namespace:Concept markup in the illustration section?

**Comment by tschmorleiz** [comment]
That is the issue, yes. Will fix.

**Comment by tschmorleiz** [comment]
Down to five issues again :smile_cat:
