### ISSUE TITLE
Slash in page title leads to error message

### ISSUE THREAD

**Issue by tschmorleiz** [101companies/101wiki#246]
We have pages that include "/". For instance:
http://mediawiki.101companies.org/wiki/Object/XML_mapping
These pages are not accessible from the new wiki anymore. For instance:
http://101companies.org/wiki/Object/XML_mapping

This must have been caused by recent changes here:
https://github.com/101companies/101rails/compare/c7c85f617a...ae36414c7e
by removing "unused code" in the router for matching URLs. 

I also realized that the same error occurs when using the API, say here:
http://101companies.org/api/pages/Object/XML_mapping
caused by these changes:
https://github.com/101companies/101rails/commit/f9ce7d40e1a0a438bff1f469e89d8eebb6d3e23c

These URL constraints are there for a reason. Please, talk to the initial authors before removing any code that you guess does not have a purpose.

**Comment by burgua** [comment]
@avaranovich already said it (about http://101companies.org/wiki/Object/XML_mapping )
I have tried to resolve this url using code of 1 week ago, 1 month age and January 2013. 
I got 404 page every time.

Here is also part of production logs (12 April):

```
Started GET "/api/pages/Object/XML_mapping/summary" for 79.211.75.129 at 2013-04-12 19:54:22 +0200
ActionController::RoutingError (No route matches [GET] "/api/pages/Object/XML_mapping/summary"):
Started GET "/api/pages/Object/XML_mapping/summary" for 141.26.71.183 at 2013-04-12 20:01:17 +0200
ActionController::RoutingError (No route matches [GET] "/api/pages/Object/XML_mapping/summary"):
```

So, I don't see any relation between this issue and recent changes. 

Actually, looks like it never worked at all.

**Comment by tschmorleiz** [comment]
I see. Since you knew that you could savely remove it, could you make it to match such pages without breaking existing matches?

**Comment by burgua** [comment]
Ok

**Comment by burgua** [comment]
Talked wit Andrei today. This functionality moved to https://github.com/101companies/101wiki/issues/250
