### ISSUE TITLE
Content gets lost on new wiki

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#248]
Please go here:

http://mediawiki.101companies.org/wiki/Equality

Now compare with this one:

http://101companies.org/wiki/Equality

Essentially, all of the illustration section is missing.

**Comment by rlaemmel** [comment]
Indeed, my lecture material disappears.
http://101companies.org/wiki/Monoid
http://mediawiki.101companies.org/wiki/Monoid

**Comment by rlaemmel** [comment]
(This was working a few days ago.)

**Comment by tschmorleiz** [comment]
Fixed.

**Comment by rlaemmel** [comment]
Equality remains lost.

**Comment by rlaemmel** [comment]
I did clear the cache again.
So the illu section is not showing.

**Comment by tschmorleiz** [comment]
When I go there, and click "Show source" or "Edit" there is no Illustration section in the source.

**Comment by rlaemmel** [comment]
Did you actually check mediawiki?
http://mediawiki.101companies.org/wiki/Equality
