### ISSUE TITLE
Introduce a "title" property for the page

### ISSUE THREAD

**Issue by avaranovich** [101companies/101wiki#250]
As discussed with @tschmorleiz , I don't see any reason to _guess_ the title from URL, because the guessing algorithm can be wrong. What I propose is to have "title" in the model of the page, that a title will be created once the user creates the page, _exactly_ following the casing

Examples:
If i create a page http://101companies.org/andrei
the title should be set to "andrei"
even if the same page would be also reachable by http://101companies.org/Andrei

please introduce the title property and handle page creation accordingly.

Please also change /pages/ API endpoint to return the list of page titles from the database, not from Mediawiki.

**Comment by burgua** [comment]
Till this time is implemented new property title for pages ( https://github.com/101companies/101rails/commits/pages ). Namespace is automatically retrieved for wiki url and saved as property 'namespace'.

Anyway need to be understood, that now any url like **/wiki/[something]** will generate page with title 'Something' (capitalized and escaped to wiki conventions)

**Ongoing are:**
- migration script for wiki pages (for namespaces: 'Contribution', 'Contributor', 'Course', 'Dotnet', 'Feature', 'Information', 'Issue', 'Java', 'Language', 'Module', 'Namespace', 'Prefix', 'Resource', 'Script', 'Service', 'Technology', 'Theme',  'Vocabulary', 'Concept', '101'])
- check permissions for creating page
- during migration all redirect pages will be ignored
- delete/rename actions

**P.S.**
In this branch already work such pages as '/wiki/Object/XML_mapping'

**Call to action**:

> the title should be set to "andrei"

Actually such naming is not classical wiki-approach. Would it be more convenient to set title as 'Andrei', as any normal wiki page?

**Comment by avaranovich** [comment]
We have 2 naming schemas:
1. ns:title
2. title

I don't see any reason why we should fix our guess anything. If the user types Contribution:haskellNovice, the ns = Contribution title =  haskellNovice.  

We could have some warning in case user has entered the namespace which doesn't exist (this might be actually an error, and we should not allow to create namespaces which don't exists).

A do see the reason to advise user on namespaces, but not on titles.
