### ISSUE TITLE
New landing page

### ISSUE THREAD

**Issue by burgua** [101companies/101wiki#254]
Here is mockup for landing page

/cc @tschmorleiz @arkadi-schmidt @rlaemmel 

![2013-06-01 15 38 35](https://f.cloud.github.com/assets/123756/594912/4e07a580-cac1-11e2-9500-0615dab2b26a.jpg)

**Comment by rlaemmel** [comment]
I like the font also.

**Comment by burgua** [comment]
Text constants

https://github.com/101companies/101rails/blob/master/config/locales/en.yml
