### ISSUE TITLE
Text constants and section titles for new landing page

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#261]
cc @burgua 

This is related to #254.

As discussed, we need several text constants and section tiles, perhaps they could be factored into a designated file.

Once the file is set up, I am happy to try filling in actual text.

So please assign to me once this the file is set up.

**Comment by burgua** [comment]
Imho, the best solution for it is using i18n scheme for Rails.
Similar approach already works here https://github.com/101companies/101rails/blob/master/config/locales/devise.en.yml

**Comment by burgua** [comment]
duplicates https://github.com/101companies/101wiki/issues/254
