### ISSUE TITLE
Some linksTo triples not rendered

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#264]
Please go here:

http://101companies.org/wiki/Quasi-quotation

This triple is not rendered:

```
 * [[kinksTo::http://en.wikipedia.org/wiki/Lisp_(programming_language)#Self-evaluating_forms_and_quoting]]
```

Is that perhaps because of "#"?

**Comment by avaranovich** [comment]
I replaced "kinksTo" with "linksTo" and it worked. So it was a typo :-)
