### ISSUE TITLE
Please release contribution submission page for testing

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#265]
cc @burgua 

So would this be here?

http://101companies.org/contribution/new

Anyway, please let me know when I (others) can start testing and whether I should take any constraints/assumptions/limitations into account for doing so. Otherwise, I would just take notes of what I see.

**Comment by arkadi-schmidt** [comment]
You can do it since Thursday.
Url will be http://101companies.org/contribute
@kevin-klein  notified, that his service is already deployed, so it would something working already.

**Comment by arkadi-schmidt** [comment]
no more actual
