### ISSUE TITLE
file markup must be rendered even if file is missing

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#270]
Look at "Architecture" of this contribution:
http://101companies.org/wiki/Contribution:haskellTree

Some filenames don't show because the files are not yet there; commit and worker cycle pending. The filenames need to be shown correctly, even if clicking them would not work.

**Comment by burgua** [comment]
Even, if smth is gone bad -> we render filename (testpage is deleted)

![bug42_20130701_163806](https://f.cloud.github.com/assets/123756/730775/2b70c2ba-e25c-11e2-9228-c7dbbc7b1f5e.png)

**Comment by avaranovich** [comment]
the question is how we distinguish really broken fragments VS those which are not yet processed by the worker.

**Comment by burgua** [comment]
I would say so:

![contributionantlrlexer_20130702_130724 png_20130702_134718](https://f.cloud.github.com/assets/123756/736182/fd93bb7e-e30d-11e2-9a5a-7bd58095cfe4.png)

**Comment by martinleinberger** [comment]
Just an FYI:
- the explorer service depends on the worker cycle to return fragments and contents of files 
- returning namespace members (which are essentially folders) depends on the existence of a wiki page - so before it can successfully return a new contribution, it needs to run the wiki2json and the members modules
- however, when just a new file is added to the existing stuff, he can return that the file exists even though there is no worker data available (provided pull101repo doesn't screw up)

=> When you have a exception on a fragment, you could ask if the file exists:
- if it does, then the worker didn't make his round yet or there is no fact extractor / fragment locator assigned
- if it does not exist, then there is a problem in the filepath or the explorer doesn't know the namespace member yet
