### ISSUE TITLE
Remove debug info from wiki pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#271]
There is stuff like this at the top:

```
 jQuery.extend($.gritter.options,{fade_in_speed:'fast',fade_out_speed:500,time:3000,});
```

**Comment by rlaemmel** [comment]
This is only visible when zooming in.
If so, then the search function also seems to be missing.

**Comment by tschmorleiz** [comment]
@burgua added gritter for notifications (https://github.com/101companies/101rails/commit/cae2b31f7082ad7ea600ce9ee25bb068c67512b5). Reassigning.

**Comment by burgua** [comment]
![51b6049ce4b0b78396d8222d](https://f.cloud.github.com/assets/123756/632885/6102c3a2-d1ee-11e2-9704-3884f2cd0e40.png)

Actually "Search bar" is hidden, but can be shown after clicking the button above.
Is it ok? Or it need to be shown in zoom mode also (if yes, please provide max zoom in percents)?

**Comment by rlaemmel** [comment]
Search needs to be somehow **easily discoverable** as in "just there".
I was always wondering what that button is for and why it is there.
cc @tschmorleiz @avaranovich
