### ISSUE TITLE
Mentions arguably to be removed from metadata section

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#274]
cc @tschmorleiz 

Unless the optimization of #256 is added, we should not list "mentions" in the metadata section. In fact, if #256 was done, then perhaps another block for "mentions" may be helpful. Perhaps we should discuss this.

**Comment by tschmorleiz** [comment]
Such triples are now excluded. We will use them for backlinks at some point, that way not depending on the MediaWiki functionality.
