### ISSUE TITLE
Renaming uses "_"

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#276]
This is a recurring issue.
As I am just renaming some features, this is a pretty serious issue.
Not sure how to clean up.
- Take any page title.
- Rename to a title with a space in the tile.
- Observe how "_" pops up in markup when the page is referenced.
- Those links go red and they show up as "_".

**Comment by rlaemmel** [comment]
For example, I leave the red "Flat_company" on http://101companies.org/wiki/Namespace:Feature

**Comment by tschmorleiz** [comment]
Two things fixed this:
- No more _ when in references when renaming
- More robust red links
- Getting rid of _ in reference names on the client
