### ISSUE TITLE
Renaming missing references

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#277]
Just renamed Feature:Nesting to Feature:Hierarchical company
Here is a page that was not affected; see the red "Feature:Nesting" link.
http://101companies.org/wiki/Namespace:Feature

**Comment by tschmorleiz** [comment]
Was just deploying, maybe interrupted. Please observe other cases. Otherwise please close.

**Comment by rlaemmel** [comment]
We might need a patch because the two features are now rather red everywhere.

**Comment by tschmorleiz** [comment]
"Hierarchical company"  I see blue. "Nesting" I can fix.

**Comment by tschmorleiz** [comment]
"Feature:Nesting" is now rewritten everywhere.
