### ISSUE TITLE
New markup for unprefixed rendering

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#278]
cc @avaranovich 

I realize that it is attractive to surpress the prefix of titles in certain context.

For instance, when I am in a section that enumerates "contributions", then the prefix should not be rendered.

Of course we can always use markup like this:

```
 [[Contribution:haskellStarter|haskellStarter]]
```

However, I would like to use a shorter phrase.

Also, the above trick breaks under renaming. The renaming will to be able to affect the rendered string.

I don't have a concrete proposal, but perhaps we can discuss on one of these days.

**Comment by tschmorleiz** [comment]
Just realized that this is already supported by our parser :dancers: 
Just use <code>[[Contribution:haskellStarter|]]</code> (with | at the end) and it will just render the title, without namespace.
