### ISSUE TITLE
Renaming broken 

### ISSUE THREAD

**Issue by tschmorleiz** [101companies/101wiki#282]
I did not touch that functionality in a few days. What currently does not work:
- Page is still accessible under old name
- References are not fixed

I suspect this happend during the recent migration/refactoring.

**Comment by burgua** [comment]
Yep, working on it.

**Comment by tschmorleiz** [comment]
You can ignore the redirect to undefined for now. Just check if the page was truly moved (name changed) and the references get fixed.
