### ISSUE TITLE
Define what text to render for a link for file markup

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#286]
This is related #285 except that this is probably an enhancement request where #285 is probably a bug report.

Please have a look here:

http://101companies.org/wiki/Contribution:haskellEngineer

Specifically, please look at this:

```
 * <file url="src/Company/Data.hs"/>: [[Feature:Flat_company]].
```

I would like the file link to be rendered as "Company.Data"? Can I express this somehow?

This is needed.

**Comment by rlaemmel** [comment]
Is there any way to express this?
I think this would be really needed.

**Comment by burgua** [comment]
So, you can add attribute name to <file> tag.

E.g. for http://101companies.org/wiki/Contribution:antlrLexer you have such markup

```
* <file url="src/main/java/org/softlang/company/features/Parsing.java" name='123'>
* <file url="src/main/java/org/softlang/company/features/Parsing.java">
* <file url="src/main/java/org/softlang/company/features/Parsiwdferng.java" name='123'>
* <file url="src/main/java/org/softlang/company/features/Parsing.java" name>
```

![contributionantlrlexer_20130702_164156](https://f.cloud.github.com/assets/123756/736957/9851bf28-e325-11e2-9915-81cd3021bfd7.png)
