### ISSUE TITLE
101wiki URLs encode space other than before

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#288]
cc @tschmorleiz @arkadi-schmidt @avaranovich 

Please consider this:

http://101companies.org/wiki/State%20monad

Should this (I presume):

http://101companies.org/wiki/State_monad

**Comment by burgua** [comment]
closed in https://github.com/101companies/101rails/commit/ac4af2cba86e6bcce6c56eae3b1b1e4f0ff4ee90
