### ISSUE TITLE
Not found endpoint page redirects to wiki

### ISSUE THREAD

**Issue by martinleinberger** [101companies/101wiki#289]
Consider the URL: 101companies.org/endpoint/Contribution:cppMPL/json

This one produces an error - Page not found. It redirects me to the wiki. Is it possible to use a 404 instead of a redirect?

Also, I'm not sure if this isn't a bug, since the [wiki dump](http://data.101companies.org/dumps/wiki.json) does know the contribution:

``` JavaScript
{
   page: {
      type: "Subject",
      page: {
          p: "Contribution",
          n: "cppMpl"
      },
   ...
   }
},
```

**Comment by rlaemmel** [comment]
One thing I notice is that Contribution:cppMpl does not have a headline but an intent:

http://101companies.org/wiki/Contribution:cppMpl

So I guess the wiki-dump functionality needs to be more gracious.

**Comment by burgua** [comment]
http://101companies.org/wiki/Contribution:cppMPL is a link to http://101companies.org/wiki/Contribution:cppMpl.
And new wiki after migration uses only 'direct' pages.

**Comment by burgua** [comment]
Now you have response with status 404: **{success:false}**

http://101companies.org/wiki/Contribution:cppMPL is not http://101companies.org/wiki/Contribution:cppMpl (last 2 chars have different case). Please use the same case for **p** and **n** like in wiki-dump.

**Comment by rlaemmel** [comment]
Don't understand.
Is that about redirects?
If so, I am in favor of getting rid of them; I guess we need to discuss this.
Anyway, please add explanation.

**Comment by rlaemmel** [comment]
Ok, I guess, now things are clear.

**Comment by burgua** [comment]
ok )
