### ISSUE TITLE
Reliable and scaleable support for github link on contribution pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#29]
It happens to me quite often that I get to contribution pages and the "Fetching link" thing never disappears.

I have discussed with Thomas and this behavior may be sometimes related to a quota issue for some involved API.

I am pretty sure that it cannot always be the issue because I am getting this behavior also when I assume everyone to sleep :-) Well, we may have enough worldwide-visitors. So it could be quota issue after all.

Anyway, this feature is important for the way how the website can be used by simple users and how I use it in courses.

We really need to get it to a reliable and scalable level.

I guess we need to rely on some server support here so that the server caches the github locations and only occasionally causes quota-relevant stuff. Perhaps, the server can used authenticated mode and thus get a better quota. Anyway, we should not break for any quota.

Let's discuss this during scrum and look for a short-term solution.

**Comment by tschmorleiz** [comment]
Solved by accessing this dump http://data.101companies.org/dumps/PullRepo.jsonp
