### ISSUE TITLE
Endpoint page for Contribution:jdbc broken

### ISSUE THREAD

**Issue by martinleinberger** [101companies/101wiki#291]
http://101companies.org/endpoint/Contribution:jdbc/json

is broken, for some reason - no clue why it is exactly this page, since others seem to work fine.

**Comment by burgua** [comment]
Some logs for it

```
NameError (uninitialized constant RDF::Sesame::Server::MalformedQuery):
  app/controllers/pages_controller.rb:129:in `block in get_rdf_graph'
  app/controllers/pages_controller.rb:114:in `each'
  app/controllers/pages_controller.rb:114:in `get_rdf_graph'
  app/controllers/pages_controller.rb:217:in `get_json'
```

And error http://take.ms/0nsAm4
Looks like @avaranovich knows this part.

**Comment by tschmorleiz** [comment]
What's special about this page is this triple:
- [[influencedBy::Contributor:Ralf Lämmel]]

"influencedBy" is not defined by means of a "Property:" page. This causes the error.

We have these pages using "influencedBy": http://101companies.org/search?q=influencedBy

@rlaemmel Is this legacy or should I add a proper property page?

**Comment by martinleinberger** [comment]
Another page that doesn't work, but that the "influencedBy" search query doesn't reveal is Contribution:richerAndroid http://101companies.org/endpoint/Contribution:richerAndroid/json

**Comment by rlaemmel** [comment]
I suggest to map influencedBy to reviewedBy.
Having too many roles, at this stage, is not really helping.

**Comment by tschmorleiz** [comment]
Agreed. Mapped the properties. In case of richerAndroid it was just some typo.
