### ISSUE TITLE
Search for "zipper" misses the actual "Zipper" page

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#292]
cc @arkadi-schmidt @tschmorleiz 

Other pages are returned.

Who come?

**Comment by burgua** [comment]
Actually, during migration of content to new wiki, we also added new search engine. And after migration search results will be so:

![wiki-seacrh](https://f.cloud.github.com/assets/123756/673411/303c9b7e-d8b7-11e2-9409-2a96e1e376d3.png)

I would like to wait for migration till Monday.

**Comment by rlaemmel** [comment]
Sounds cool.
Looking forward the new search.

**Comment by burgua** [comment]
new search is implemented and deployed
