### ISSUE TITLE
Backlinks broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#293]
Please have a look here:

http://101companies.org/wiki/Zipper

It lists some vocabulary pages as linking back to Zipper, but they don't do.

I see this sort of wrong backlinks a lot.

**Comment by rlaemmel** [comment]
I am just re-saving those pages which are listed wrongly as linking back. Then the vacuous backlinks go away.

**Comment by tschmorleiz** [comment]
Can you provide another pages with broken backlinks, please?

**Comment by rlaemmel** [comment]
I believe that this was an intermittent problem.
I remembered one other case where I noticed this sort of strange behavior and that one "fixed itself".
So I am closing.
