### ISSUE TITLE
Popup for links with namespace '101'

### ISSUE THREAD

**Issue by burgua** [101companies/101wiki#294]
Actually any link to pages [@data](http://101companies.org/wiki/@data), [@project](http://101companies.org/wiki/@project) e.t.c (from 101 namespace)  don't have popups. 

/cc  @avaranovich 

Client sends such kind of request with response 500

```
http://101companies.org/resources/concepts/@project?format=jsonp&callback=jQuery18207824814096093178_1371649255986
```

But next need to be sent 

```
http://101companies.org/resources/101/@project?format=jsonp&callback=jQuery18207824814096093178_1371649255986
```

**Comment by tschmorleiz** [comment]
If you look at the actual source you will see that requests are sent to:
<code>http://101companies.org/resources?format=jsonp&wikititle=TITLE</code>
So for [@data](101companies.org/wiki/@data) the request goes to:
<code>http://101companies.org/resources?format=jsonp&wikititle=@data

What you see is the rewritten URL by the worker.

This means that @ is not handled by the discovery service. @martinleinberger, can you add this case please?

**Comment by martinleinberger** [comment]
Alright, so the redirect I return http://101companies.org/resources?format=jsonp&wikititle=@data is wrong. I'll fix it.

**Comment by martinleinberger** [comment]
Should be fixed.
