### ISSUE TITLE
URL compression for linksTo/identifies too brutal

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#295]
Please go here:

http://101companies.org/wiki/Functor

Please observe this metadata:

```
 * [[identifies::http://www.haskell.org/haskellwiki/Functor]]
 * [[linksTo::http://www.haskell.org/haskellwiki/Category_theory/Functor]]
```

They are rendered the same (which is, of course, confusing).

**Comment by tschmorleiz** [comment]
So what should the general schema be?

**Comment by rlaemmel** [comment]
I would simply check whether your existing compression creates a clash.
Whenever this is the case, simply "show all" as fallback.
This will only happen in a very rare cases.
