### ISSUE TITLE
Major hickup with [[...|]] notation

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#296]
cc @burgua @arkadi-schmidt 

Suddenly the wiki started expanding [[foo|]] to [[foo|foo]] when saving.

This effectively kills renaming.

**Comment by rlaemmel** [comment]
See here:

http://101companies.org/wiki/Namespace:Namespace

**Comment by tschmorleiz** [comment]
Working on this one.

**Comment by tschmorleiz** [comment]
It seem like this always happend. This is actually mediawiki, expanding the link when saving.

**Comment by rlaemmel** [comment]
It did not happen universally.
It is important that it is never expanded.

**Comment by tschmorleiz** [comment]
I changed is such that [X:Y|Y] is always rewritten to [X:Y|]. That is, it is only expanded when the link name and suffix match exactly.
