### ISSUE TITLE
Improve rendering when resolution errors occur for "file" markup

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#297]
cc @arkadi-schmidt @tschmorleiz 

Please see here:

http://101companies.org/wiki/Bug42

Please remove the page once this issue is resolved.

**Comment by burgua** [comment]
So it looks now (page is deleted)

![bug42_20130701_163806](https://f.cloud.github.com/assets/123756/730769/fa8b8978-e25b-11e2-840f-f5c205eba069.png)
