### ISSUE TITLE
" " in URLs

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#298]
cc @arkadi-schmidt @tschmorleiz @avaranovich 

We want to use "_" for " " in URLs, right?

But when entering " ", it gets translated like this:

http://101companies.org/wiki/Zipper%20monad

**Comment by avaranovich** [comment]
This is a bug, should be automatically redirected to Zipper_monad

**Comment by tschmorleiz** [comment]
Yes, we had some URL rewriting before.

**Comment by rlaemmel** [comment]
This is still an issue.
http://101companies.org/wiki/Course:Programming%20in%20Koblenz
Is this well assigned to @burgua and @arkadi-schmidt ?
