### ISSUE TITLE
Tables in wiki markup

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#299]
cc @arkadi-schmidt @tschmorleiz @avaranovich 

Just looked at this:

http://101companies.org/wiki/Language:HTML5

The rendering of the table looks a bit strange.

Question to Thomas specifically, do we want to support table markup syntax proper?

(Actually, this particular wiki page needs some maintenance anyhow. Perhaps we can win back Tobias to improve some of his content.)

**Comment by tschmorleiz** [comment]
Table-syntax in wikitext is pretty strange, but I think people might expect to be able to use it. I think we should properly support it.

**Comment by tschmorleiz** [comment]
Please have a look at the page.

I applied some bootstrap magic and changed the font-size. Not sure about the font though, maybe we should rather ask Tobias to make the table more compact.

Any opinions?

**Comment by rlaemmel** [comment]
Technically this looks good now.
Not high prio to have super-robust support.
So I am closing.
Thanks!
