### ISSUE TITLE
Edit sections

### ISSUE THREAD

**Issue by avaranovich** [101companies/101wiki#3]
User should be able to edit page sections.

**Comment by tschmorleiz** [comment]
To enable editing and saving the server needs to support PUT requests, which backbone uses to update/save models.

**Comment by avaranovich** [comment]
@tschmorleiz please specify the interface(s) for PUT. Is that about the sections only?

**Comment by tschmorleiz** [comment]
The URL is the same as for GET requests: http://localhost:3000/api/pages/**pagename**/sections/**sectionname**. Data is sent in JSON, same structure as the data received via GET. For now I only need support for sections.

**Comment by tschmorleiz** [comment]
Works.
