### ISSUE TITLE
Top-level area (with search, login) behaving strangely

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#302]
cc @arkadi-schmidt @tschmorleiz 

Please test with different browsers and resolutions.

I get strange behaviors quite often. In particular, it is not good when this area occupies a significant part of the screen without any obvious way of getting rid of it. Also, the gesture for actually showing the area (this icon with many lines) isn't very suggestive; it also kicks in when I zoom in / out, but why would it do it?

Perhaps we need to discuss this tomorrow.

**Comment by burgua** [comment]
Navbar area looks so now, if you use 150% zoom
(logo + search field + user menu) placed in 1 line

![101project_20130720_162707](https://f.cloud.github.com/assets/123756/830356/94a6f7d6-f148-11e2-8f3f-be135f8c34f6.png)
