### ISSUE TITLE
Rendering (linebreaks) broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#303]
http://101companies.org/wiki/Contribution:jdbc

See where this occurs:

```
 Follow the steps described here [[Contribution:mySqlMany]] to set up the company database. That is, stop after populating the tables. 
```

Characters are cut off.

I tried this with both Chrome and Firefox and different zooms.

Is this some markup problem?

**Comment by burgua** [comment]
CSS-Problem

**Comment by tschmorleiz** [comment]
Yep, that is was.
