### ISSUE TITLE
No content must be lost upon save

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#308]
cc @arkadi-schmidt @burgua 

I just saved a (long) page with a markup error of this form:

```
    === A header not closed
```

Everything beyond this point got lost.

Generally, really nothing should be lost upon save.

**Comment by tschmorleiz** [comment]
Did you save a section or a whole page?

**Comment by rlaemmel** [comment]
Whole page. (I mostly work in "whole page" mode when authoring content as it tends to touch several sections. I use "edit section" for patching.)

**Comment by rlaemmel** [comment]
So my assumption is that the missing "===" somehow confused the parser.
However, it didn't throw away the metadata section that followed.
So perhaps I was editing the illustration section. I can't say for sure.

**Comment by tschmorleiz** [comment]
Parsing issue indeed. The correct content is saved, but when retrieving sections the parser only gives us the content up to the part you mentioned. Working on this one.

**Comment by rlaemmel** [comment]
This needs to be solved in a simple and universal way.
The parser must not ever loose any chars.
If the parser does not know further, then a general fall back must apply so that all chars contribute to the current section.

BTW, does the parser and the page model work ok with pages without any section headers? If not, it should, otherwise we don't have a general solution.

**Comment by burgua** [comment]
I will have time for it in 1 week.

**Comment by rlaemmel** [comment]
@tschmorleiz 

@burga was just showing me the problem _again_.

It looks like it is not in the server-side parser but on the way to or on the side of the client.

Anyway, looks like this in your code.

This code looks rather hard to edit for anyone but you.

More generally, can you fight this down (even when I am not making sense about the guessing here).

Ralf

**Comment by tschmorleiz** [comment]
I just tried to reproduce and created a page with such incorrect syntax. Please look here:

http://101companies.org/api/pages/Issue:Parsing1

As you can see the _content_ was saved as expected, but the it is not correctly parsed into _sections_.
This is the JSON is use to display pages, I don't modify or reparse it, I just the the source and the parsed source that the server provides.

It should be split into two sections even though a subsection is not closed.

**Comment by tschmorleiz** [comment]
@burgua, do you have an idea why the parser might behave so badly? I guess we can fight this down.

**Comment by burgua** [comment]
Parse entire page and split in sections by <h[N]> on the client?

**Comment by tschmorleiz** [comment]
Why would the client do that? All parsing is done on the server, so splitting the resulting HTML into sections on the client seems strange. Also, the JSON needs to directly correspond to the model of pages we have on the client, where a page has a list of sections.
I think we should just get the existing functionality (splitting on server) back to working.

**Comment by rlaemmel** [comment]
I suggest to treat this issue as non-high prio, but it would be good to hear whether the issue is correctly assigned to @burgua or whether @tschmorleiz should be assigned.

**Comment by tschmorleiz** [comment]
I slightly changed the parser. Now, when a line starts with header syntax "={2,6}" missing trailing "="s are completed. This makes things more robust and should fix this issue.
