### ISSUE TITLE
Headline pop-up broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#309]
cc @arkadi-schmidt @burgua 

I was just playing here:

http://101companies.org/wiki/Technology:QuickCheck

If I would hover over "Haskell" or "testing" then eventually it would say this:

Page not found.

**Comment by martinleinberger** [comment]
No bug - the complete 101worker system (and therefore the 101explorer, and therefore the wiki popups) seems to be down: http://data.101companies.org/

**Comment by burgua** [comment]
Actually, any popup will show  'Loading' and 'page not found' because worker.101companies.org is down.

**Comment by tschmorleiz** [comment]
Confirmed, this happens due to the down worker.

**Comment by tschmorleiz** [comment]
Did further investigation and it appears the discovery service (which is used for headlines) is broken in terms of the redirect functionality. Use this URL to reproduce:

http://101companies.org/resources?wikititle=Testing&format=jsonp

**Comment by tschmorleiz** [comment]
In fact, using the URL this should redirected to I also get some error:

http://101companies.org/resources/concepts/Testing?format=json

**Comment by martinleinberger** [comment]
nginx errors are not related to the discovery service. nginx is one step before the discovery service.

This is still related to the downtime of 101worker and that the URLs related to 101worker are not yet functional.

edit: 101worker simply got a new IP and if I understand this right, it just takes some time until the DNS services are aware of that. (Proof: http://data.101companies.org/dumps/ )
