### ISSUE TITLE
Content gets lost on save

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#310]
I had this now twice and each time I have lost substantial amount of work. Basically, when saving a page, it happens that all changes are ignored and the page returns as before. I don't understand when this happens, but we need more robustness here.

**Comment by rlaemmel** [comment]
I found the culprit.

Save fails to save when we have this:

```
  <fragment url="http://101companies.org/resources/contributions/tabaluga/src/Company/Cut.hs/pattern/cut"/>
```

We should have this:

```
  <fragment url="/contributions/tabaluga/src/Company/Cut.hs/pattern/cut"/>
```

So this is also an issue that @martinleinberger needs to address because the wrong markup comes right from the explorer (from the "absolute markup" item).

Anyway, please do not NOT save.

**Comment by martinleinberger** [comment]
Should be fixed. Can you confirm that it is now as intended?

**Comment by martinleinberger** [comment]
I assume that this is solved, therefore I'll close this issue. Please reopen if there are still problems.
