### ISSUE TITLE
CCS or something related in misery?

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#312]
cc @burgua @tschmorleiz @avaranovich 

Did you guys change something in the CSS or related stuff?

When **editing** wiki pages I get strange cursor positions.

Just restarted Chrome and things changed, but they are still weird.

How to reproduce? Just edit any page and see where the cursor shows relative to the true position.

**Comment by rlaemmel** [comment]
I also tried Firefox because editing is rather impaired this way.
Same problem.

**Comment by tschmorleiz** [comment]
This happened due to recent CSS changes. Will fix.

**Comment by rlaemmel** [comment]
It is not fixed as far as I can tell.

**Comment by tschmorleiz** [comment]
Hm, when I go to some random page and hit edit the cursor writes where it is.

**Comment by rlaemmel** [comment]
1. Please load some page.
2. Try to double-click all words of the headline one, after another.
3. Observe how the wrong strings get focused.

**Comment by rlaemmel** [comment]
This may depend on zoom level.

**Comment by burgua** [comment]
Application is need to be developed from perspective of using (latest Chrome, 150% zoom). So I fixed it. Pretty strange and interesting issue by the way, ace-editor couldn't be used, if editor is wraped with DOM-element, that uses non-monospaced font.
