### ISSUE TITLE
Finish contribution integration for the F# contributions

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#314]
cc @burgua 

@MightyNoob is just sitting here and we talk about how to finalize his project.

As you were working with him on the contribution process, please finish as follows:
- The actual contributions are here: https://github.com/MightyNoob/contributions
- They are not registered in .gitdeps; please add.
- There are duplicates; please see here for all the FSharp contributions: http://101companies.org/wiki/Language:FSharp Please remove those copies whose names start in "upper case".

**Comment by burgua** [comment]
Duplicates removed,
added repos to .gitdeps in 101repo
Contributions of @MightyNoob : http://101companies.org/users/51a0c56ad54b7b301d000003
