### ISSUE TITLE
Finalize contribution integration for DWH stuff

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#315]
cc @burgua 

@ydupont is just visiting.

He has this contribution:

http://101companies.org/wiki/Contribution:pyDWH

I understand that Yves was also playing with your contribution page.

Let's stop this for him so that we can link his stuff now.

I am explaining him now how to use .gitdeps.

**Comment by burgua** [comment]
@ydupont hasn't worked with contribution page.

To link his contribution to wiki page he need to visit http://101companies.org/contribute/new
and create actually the contribution using his repo pyDWH

As contribution title he needs to use 'pyDWH' (it will be actually used automatically).
His contributions will be available via http://101companies.org/users/5173be15d54b7bf443000009

**Comment by ydupont** [comment]
Actually I did work with it, but AFAIR it took some time for the page to load. The first time it timed out completly.
I will retry to post it via "contribute/new" once I reorganized the repository.

Cheers,
Yves

**Comment by rlaemmel** [comment]
Seems to work now.
