### ISSUE TITLE
contributor names and pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#318]
cc @burgua 

@avaranovich and @tschmorleiz : we need your comment on this one.

Until now, we assume that contributors should get / have a page in the "Contributor" namespace where we use the pattern "FirstName LastName". 

We need to rethink and improve on this front.

Some observations:
- We should not require from contributors that they create pages.
- We sort of do need pages, though because we want to be able to link to contributor pages with semantic properties such as "developedBy".
- We do get to know about some contributors via the contribution submission system. There is no guarantee that we have FirstName LastName for those github users. Perhaps we should ask for it during the submission process? However, people change their mind. So it should be possible to change names.
- We will not know all of the contributors just by means of the submission process because we may have pieces of collaborative work and then more developers would need to be added. So basically, the mongodb db only knows submitters but not necessarily developers.

So how do we go about this?

**Comment by avaranovich** [comment]
Why not to use github username? It is also unique. If the user wants -- he can add the real First/Last name to his profile on 101companies. 

The process of getting "developers" boils down to querying the github repo and selecting all users who pushed code.

**Comment by burgua** [comment]
is part of https://github.com/101companies/101wiki/issues/323
