### ISSUE TITLE
Handle all users

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#319]
I guess we need to do this:
- Ask old users for their github id.
- Ask them to take back their contributions into their github space, when appropriate.
- Ask them to add 101companies and others as collaborators.

**Comment by burgua** [comment]
@rlaemmel is it still actual, when we will do https://github.com/101companies/101wiki/issues/317 ?
It looks no more actual now.

**Comment by burgua** [comment]
if part of https://github.com/101companies/101wiki/issues/323
