### ISSUE TITLE
What is the conceptual design of the contributor page?

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#324]
cc @burgua @tschmorleiz @avaranovich 

http://101companies.org/users/519e1329d54b7bdc6200000b

This sort of page is becoming important!

So we need to think deep and proper as to what it should show and how to obtain the information.

Could you please prepare a proposal that we can discuss offline from github through email and during team meetings?

**Comment by burgua** [comment]
is part of https://github.com/101companies/101wiki/issues/323
