### ISSUE TITLE
wiki endpoint too slow

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#328]
cc @tschmorleiz @martinleinberger 

This may relate to #325 

I just tried a few times this.

I explored: http://101companies.org/resources/contributions/antlrAcceptor?format=html

Then I clicked endppoint: http://101companies.org/endpoint/Contribution:antlrAcceptor/json

Just got a server error.

Before that I got a very slow response.

**Comment by rlaemmel** [comment]
When I discussed this last week with @burgua and also from my observation, this was still a big issue.
It looks like the endpoint is occasionally failing and very slow.
What is the status here?
Is the problem understood?
Do we need to redesign?
@burgua , any ideas how to drive this issue to closure?
I understand that this may be a non-trivial problem.

**Comment by burgua** [comment]
Problem is clear, trivial and in work since yesterday (https://github.com/101companies/101rails/tree/dev)
2 days are needed to solve it.
Reassigning to me.

**Comment by burgua** [comment]
@rlaemmel 
performance is improved.
Acceptable now?

**Comment by rlaemmel** [comment]
Ultimately, a perf test may help here.
What I saw I liked.
Thanks!
