### ISSUE TITLE
Lowercase namespaces in internal links

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#33]
Thomas, I am assigning this and some other issues to you --- not knowing very well, whether Andrei would be more appropriate. Please sync with Andrei, if necessary.

This is about a really simple bug:

Go here:
http://beta.101companies.org/wiki/Contribution:haskellComposition
Then go to relationships and click the first link for Contribution:haskellVariation.
This is the actual link, which uses lower case:
http://beta.101companies.org/wiki/contribution:haskellVariation

Amazingly, the link is sort of resolved this way, but then all metadata is missing on the page because, I guess, it continues to work with lower case.

**Comment by tschmorleiz** [comment]
Fixed.
