### ISSUE TITLE
backlinks feature holding back mediawiki shutdown

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#330]
cc @avaranovich 

Please push this through so that @burgua and @arkadi-schmidt can proceed.

**Comment by tschmorleiz** [comment]
We agreed @burgua would implement that backlinks are directly stored in the model that is persisted in mongoDB.

**Comment by burgua** [comment]
This question need clarification -> we need sync with sesame store @avaranovich 

Feel free to help with this here https://github.com/101companies/101rails/blob/dev/app/models/page.rb#L54

**Comment by tschmorleiz** [comment]
I think all functionality to store the page in RDF is implemented. But indeed, we should refactor that code to that method you pointed to.

**Comment by burgua** [comment]
Retrieved all info I need from @avaranovich . I do it further

**Comment by burgua** [comment]
And now closing it.
