### ISSUE TITLE
perf tests for the 101wiki

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#331]
cc @arkadi-schmidt @avaranovich @tschmorleiz 

I guess we should discuss this topic a bit.

Since performance of basic page browsing / editing is going down time and again and this is not surprising, I would like to propose that we automate some basic perf testing so that we don't need to rely on user reports like this.

Any ideas?

**Comment by burgua** [comment]
depends on https://github.com/101companies/101wiki/issues/336

**Comment by rlaemmel** [comment]
We close this for now as @arkadi-schmidt and @burgua have covered this topic to some extent in the thesis. In their presentation, they should help us understand how we can maintain and improve engineering in this regard.
