### ISSUE TITLE
Working links are rendered red

### ISSUE THREAD

**Issue by martinleinberger** [101companies/101wiki#333]
After some renaming, some working links are rendered red. Currently this happens on 
- the [IO behavior](http://101companies.org/wiki/IO_behavior) page, in the description section, the IO behavior link
- the [Pure IO behavior](http://101companies.org/wiki/Pure_IO_behavior) page in the headline (again, a link to IO behaviour)
- also on [Impure IO behavior](http://101companies.org/wiki/Impure_IO_behavior) - I feel like IO behavior is key here

**Comment by burgua** [comment]
No more actual after stoping work with mediawiki
