### ISSUE TITLE
101integrate links are broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#334]
cc @avaranovich 

Please go here:

http://101companies.org/wiki/Monad

Then hover over the Haskell books.

Nothing happens.

**Comment by tschmorleiz** [comment]
Should be fixed.

**Comment by rlaemmel** [comment]
http://101companies.org/wiki/Monad

The book references are unfoldable for as long as metadata has not completed loading.

Once the page is loaded completely, when hovering over the book names, nothing happens.

**Comment by rlaemmel** [comment]
Just for clarity.

Try loading Monad; try hovering over the books.

The book items will not unfold; the other times do unfold.

![image](https://f.cloud.github.com/assets/1208815/1011849/436271f8-0b64-11e3-83fd-8d099fddeee0.png)

**Comment by tschmorleiz** [comment]
Please try.

**Comment by rlaemmel** [comment]
Works. Thanks.
