### ISSUE TITLE
Reset of wiki articles

### ISSUE THREAD

**Issue by ydupont** [101companies/101wiki#335]
Hello Thomas,

cc @avaranovich 

last week (03.08 - 05.08) I worked on several wiki articles.
Today I saw that they somehow got reset. One page I created isn´t even there anymore. The other one has lost all it´s edits.

http://101companies.org/wiki/Contribution:pyDWH (lost edits)
http://101companies.org/wiki/Feature:Dimensionality (lost page)

BTW: In case I assigned the issue to the wrong person please reassign.

Thanks & Cheers,
Yves

**Comment by tschmorleiz** [comment]
Hey Yves,

was the page saved at some point during the time you edited?

**Comment by burgua** [comment]
@ydupont is it fixed now?

**Comment by ydupont** [comment]
Hey guys,
now it looks like I left it!

Thanks

**Comment by burgua** [comment]
@ydupont can you close if it's ok?

**Comment by ydupont** [comment]
@burgua yes, its complete. Thanks for the quick help.
