### ISSUE TITLE
Eliminate per-section loading

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#336]
cc @tschmorleiz 
cc @avaranovich 
cc @arkadi-schmidt 

We are sitting on this already for a while. Our load perf is not acceptable. (I cannot say much about current save perf.)

I am pretty confident that one huge perf issue is the **per-section load approach** which leads to too many requests which in turn lead to connection congestion and and a quasi-synchronous/sequential loading behavior.

Happy to be wrong, but something needs to happen here, one way or another.

So I propose that Arkadi and Alex look into this, as they seem to be most motivated and most available to do this and Andrei and Thomas help at all levels as good as they can. **For the start, it would be good to get some profound input/advice from Thomas and Andrei via comment to this issue.**

**Comment by avaranovich** [comment]
Think about this: many sections contain fragments. Rendering fragments involves fetching the content from 101explorer and rendering it using the right language syntax. If the whole page is rendered on the server, then the rendering time = rendering wiki content + getting all fragments from 101explorer + rendering all fragments.  
At this point, we don't have any evidence, that async rendering is really the source of the issue.

**Comment by rlaemmel** [comment]
I am closing this for now because
the perf seems to be Ok for now
which is presumably the result of several, other changes by @burgua and @arkadi-schmidt.
Let's keep an eye on this.
