### ISSUE TITLE
Metadata incompletely listed

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#337]
cc @avaranovich 
cc @burgua 
cc @arkadi-schmidt 

Please go here:

http://101companies.org/wiki/Contribution:haskellStarter

Please observe:

<pre>
* [[implements::Feature:Flat company]]
</pre>

Now go here:

http://101companies.org/wiki/Feature:Flat_company

Contribution:haskellStarter is not listed in the metadata section.

![image](https://f.cloud.github.com/assets/1208815/992918/ad2f4500-098b-11e3-90aa-826160935da7.png)
![Uploading image.png . . .]()

**Comment by rlaemmel** [comment]
Just to explain further, loads of metadata is missing.
For instance, look here:
http://101companies.org/wiki/Feature:Mentoring
It looks like there is no implementation of mentoring which is not true of course.
Here is one:
http://101companies.org/wiki/Contribution:haskellProfessional

Could it be that perhaps that only outgoing metadata is listed (with this as subject)?

**Comment by burgua** [comment]
> Could it be that perhaps that only outgoing metadata is listed (with this as subject)?

Yes, according to implementation.

**Comment by tschmorleiz** [comment]
Yes, we only list outgoing metadata, but still this "implements"-triple is missing. Will look into it next week.

**Comment by rlaemmel** [comment]
Sorry don't understand. 
We always listed both ways.

**Comment by tschmorleiz** [comment]
Listed in the source of the document.

**Comment by tschmorleiz** [comment]
In fact, http://101companies.org/endpoint/Monad/json only contains outgoing triples. I am pretty sure though that this was not touched by me in quite some time. @avaranovich Did you change something?

**Comment by burgua** [comment]
I changed smth and I know how to solve.
Reassigning.

**Comment by burgua** [comment]
@rlaemmel @tschmorleiz @avaranovich missed smth now?
If not -> you can close it.

**Comment by rlaemmel** [comment]
Looks great again
