### ISSUE TITLE
Semantic back links

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#34]
Thomas, I am assigning this and some other issues to you --- not knowing very well, whether Andrei would be more appropriate. Please sync with Andrei, if necessary.

Didn't we have semantic backlinks at some point where "this" is the object as opposed to the subject?

Don't see this on the pages I tried.

**Comment by tschmorleiz** [comment]
Ralf, can you please provide a link to a page where you think such triples are missing?
A working example: http://beta.101companies.org/wiki/Monad

**Comment by rlaemmel** [comment]
Yes, @tschmorleiz , I was noticing that the other direction of semantic links kicked in again.
I am closing therefore.
