### ISSUE TITLE
pages load incompletely and slowly

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#340]
cc @tschmorleiz @martinleinberger 

Just tried this

http://101companies.org/wiki/Contribution:haskellEngineer

(after @avaranovich had informed about the worker to be back again).

It loaded section by section very slowly.

More importantly, it got stuck at the "Illustration" section.

![image](https://f.cloud.github.com/assets/1208815/1041038/921b515e-0fc7-11e3-9e62-76fbad1f2894.png)

**Comment by burgua** [comment]
Reloaded nginx for 101rails/wiki.
Now new IP of worker will be resolved.
Section "Illustration" works for me

**Comment by rlaemmel** [comment]
See screen grab below.

Illustration loads somehow (after waiting like 10 secs) but it's screwed up.

In addition, the page finishes loading only after like 1 min.

![image](https://f.cloud.github.com/assets/1208815/1047840/50f622d4-107c-11e3-992a-dbf803127acf.png)

**Comment by rlaemmel** [comment]
I should probably add that I remember the wiki client did render things like shown above (i.e., sort of listing a table of contents) already some time ago. @tschmorleiz fixed this.

Further, I should add that it took nearly 10 seconds even for anything to show in the section.

Below, the table of contents, things are rendered fine, btw.

**Comment by burgua** [comment]
I forgot about part with removing toc (table of contents) - will update today.

**Comment by burgua** [comment]
Toooo old
