### ISSUE TITLE
Add help for adding  a code snippet

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#341]
So this should add a button to this editing view:

![image](https://f.cloud.github.com/assets/1208815/1049620/136ab1c2-10aa-11e3-9e76-6ce7255399a6.png)

The button could be called "Code".

It should insert something like this:

```
 <syntaxhighlight lang="???">
```

**Comment by tschmorleiz** [comment]
You can also highlight some code with your cursor and then press the button. That will enclose the code with the tags.

**Comment by rlaemmel** [comment]
Cool
