### ISSUE TITLE
Cannot add pages anymore

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#342]
cc @tschmorleiz @burgua @arkadi-schmidt 

Go here:

http://101companies.org/wiki/Contribution:haskellScott

Click "Scott Encoding" (which is red).

I had two different behaviors:
- First the loading of the empty page didn't terminate; the edit button would never show.
- Once I tried again, I would get this error:

![image](https://f.cloud.github.com/assets/1208815/1049685/f7f897ea-10ab-11e3-8d03-08f3baae837e.png)

and be taken to http://101companies.org/wiki/@project

So one cannot add pages anymore.

**Comment by burgua** [comment]
Looks resolved now

**Comment by burgua** [comment]
@rlaemmel could you close it, if it works ok?

**Comment by rlaemmel** [comment]
Thanks
