### ISSUE TITLE
Explorer and data links as well page title

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#35]
Thomas, I am assigning this and some other issues to you --- not knowing very well, whether Andrei would be more appropriate. Please sync with Andrei, if necessary.

Go to any beta... page.
There is a "Data" link; it does not direct to "data.101companies.org".
There is an "explorer" link; neither does this direct anyway.

Please also fix the title, which is currently "wiki".
Call it "101wiki" perhaps

**Comment by tschmorleiz** [comment]
Explorer tab disabled for now.
