### ISSUE TITLE
Properties missing for some pages

### ISSUE THREAD

**Issue by avaranovich** [101companies/101wiki#350]
these pages don't have required properties (e.g. 'page_title_namespace') stored in the database:

Function_composition
## Function_composition

101demonstration
101implementation
101model
Foo
Foo1234
Foo17
Foo18
Foo3
Fooo123
Foop
Foop1
Foop1234
Foop12345
FoopNEW
Foop Bar2
Foop module
Foopbarss
Foops
Foops2
NewFoop
·
fsharpContributionMightyNoob
mySqlOneExtended
template
Annual employee review
Bonus
Job description
Parser combinators
Namespace:Vocabulary
Script:Functional_data_structures
Script:Monads
Data_type
Script:Functors_and_friends
Script:Higher-order_functions_in_Haskell
Feature:Ranking
Total_order
Semantic_equality
Structural_equality
Monad/json
Foo
@worker
@wiki
Monad/json
Object/XML-mapping
Lämmel
burgua
DeletePage
DeletePage
Foop2
First steps in Haskell
Basic software engineering for Haskell
Basic software engineering for Haskell
Basic software engineering for Haskell
cppMPL
cppMPL
cppMPL
BurguaTest
Testerpage3
Testerpage2
Testerpage
developedBy
uses
implements
BurguaTest2
101implementation
BurguaTest3
Admin
Bug42
Broken
Suboptimal
101main
Unspecific version
101proposer
Clear vk
Mir
Yandex
Jquery
Test1
Shadow
Zzzz
Murka
TestStuff
C9 Roadmap
Vk
Bug42
Sshh
Grittes
pythonDjan
FsharpRecords
FsharpClasses
FsharpNonMonadicLogging
Gritter
Dots
Railsroady
Notices
Cler vk
Dotiles
Notices
New shadows
Miry
Serials
Framework
Dots
101
Omnifocus
Frame
@proejct
Pomodoro
Railsroady2
My serials2
101railz
51e41fedd54b7b85a0000002
pythonDWH
51c838c8d54b7bd5a4000001

Most of them are dummy and can be removed. But for some of them, this is a bug.

**Comment by burgua** [comment]
I assume, that these pages were found using **direct** access to mongodb.
You need to filter them. Deleted pages have non-empty property **deleted_at**.
You can read more here: http://mongoid.org/en/mongoid/docs/extras.html#paranoia
