### ISSUE TITLE
Cannot use 101companies@gmail.com on the wiki page

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#351]
cc @arkadi-schmidt 

101companies@gmail.com

is rendered as 

101gmail.com

**Comment by rlaemmel** [comment]
On this page, I am using -at- instead of "@" to make the bug disappear.

http://101companies.org/wiki/@repo

cc @tschmorleiz

**Comment by tschmorleiz** [comment]
This was client-sided, so I closed it.
