### ISSUE TITLE
parOf not working

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#356]
cc @avaranovich 

I don't think this is a bug bc we are not at the point that new properties work magically; perhaps such magic is needed. Certainly, support for "partOf" (see below) is needed.

Look here:

http://101companies.org/wiki/Technology:GHC

It declares itself to be part of Haskell Platform.

Now look here:

http://101companies.org/wiki/Technology:Haskell_Platform

No mentioning of GHC.

**Comment by avaranovich** [comment]
Just thinking in loud. This example is actually quite different from Controller partOf Ruby on Rails. In this case GHC "kind of" exists w/o Haskell platform. At least these are 2 different pages.

**Comment by rlaemmel** [comment]
That's good.
It's like aggregation versus composition.
The difference would be evident from the URL.

**Comment by rlaemmel** [comment]
I have been starting to use derivesFrom.
http://101companies.org/wiki/Contribution:haskellWriter
So this is another new property.

**Comment by rlaemmel** [comment]
After talking to Andrei, we may rather compute such metadata as derivesFrom.
So I removed it again.

**Comment by burgua** [comment]
closed with https://github.com/101companies/101wiki/issues/399
