### ISSUE TITLE
identifies->sameAs, linksTo->similarTo

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#360]
This is how we should rename the predicates.

While renaming all current "linksTo" to "similarTo", we will keep "linksTo" around as the most unstructured relationship. Data cleaning could go over "similarTo" triples at some point and see whether any of those should be "linksTo". Experience tells me that the majority is "similarTo".

**Comment by tschmorleiz** [comment]
I guess this does no longer apply?

**Comment by avaranovich** [comment]
No, we don't do any automatic renaming.
