### ISSUE TITLE
Code rendering on wiki missing

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#364]
cc @burgua 
cc @martinleinberger 
cc @avaranovich 
cc @tschmorleiz 

It looks like code snippets are not rendered anymore.

http://101companies.org/wiki/Contribution:haskellStarter

![image](https://f.cloud.github.com/assets/1208815/2307017/0f4beff2-a29f-11e3-8400-1a8c1fb7889c.png)

**Comment by martinleinberger** [comment]
Is directly related to this issue: https://github.com/101companies/101worker/issues/171
That's why I'm closing this one.
