### ISSUE TITLE
media link not working

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#376]
cc @arkadi-schmidt 

Can you please fix this as soon as possible?

http://101companies.org/wiki/@system

See the broken link.

![image](https://cloud.githubusercontent.com/assets/1208815/2788343/f6541578-cb99-11e3-96bc-ad252fb8deb0.png)

**Comment by rlaemmel** [comment]
I am adding the link in clear text for now so that students can find the file anyway.

**Comment by rlaemmel** [comment]
For robustness of the viewer and discoverability of the link, it would be good to show the link anyway  or make it discoverable / copy/pastable when hovering over it.

**Comment by burgua** [comment]
In this case we have pdf-file with one page. Page contains only one image.
We have two options.

**1**. if you want use **pdf-file**: you can upload this pdf-file to slideshare. After that you can embed it into the page like it was done here:
http://101companies.org/wiki/Script:Metaprograms_and_metadata
In this case you will also have download link.

**2**. Or you can host this image elsewhere as **image** (e.g. github) and embed into page using such syntax.

```
[[media:https://dl.dropboxusercontent.com/u/795699/pic.jpg]]
```

You should have similar result.
http://101companies.org/wiki/AngryBird 

Please close, if it's ok.

**Comment by rlaemmel** [comment]
I agree with the option to move from .pdf to .jpg.
In fact, I have just done this.
So I am closing.
