### ISSUE TITLE
Backlinks are missing on some pages

### ISSUE THREAD

**Issue by burgua** [101companies/101wiki#379]
For example 
http://101companies.org/wiki/Vocabulary:Functional_programming

There should be an "empty" backlinks section or other means of indication there is no backlinks

**Comment by rlaemmel** [comment]
@avaranovich we discussed this in a meeting just now. 
Is this lack of an empty backlinks section still wanted with the current 101wiki version?
To me it looks like, we don't need such an empty section.
Close?

**Comment by burgua** [comment]
Closing, since no interest/reason from requester.
