### ISSUE TITLE
Fragment markup on the new wiki

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#38]
Andrei, I am assigning this and some other issues to you --- not knowing very well, whether Thomas would be more appropriate. Please sync with each other, if necessary.

I wonder whether now is the time to enable fragment markup in the pages?
- We are editing a lot these days; chances are that we properly use the feature.
- It would be very nice to talk about in the paper, but I guess we can wait a few more days.

**Comment by avaranovich** [comment]
duplicated.
