### ISSUE TITLE
New contribution not found by 101explorer

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#383]
cc @arkadi-schmidt @burgua @Mpaul138 

http://101companies.org/resources/contributions/jxpath?format=html

![image](https://cloud.githubusercontent.com/assets/1208815/2902809/2b81bb42-d5ea-11e3-9ab6-57df97f2318e.png)

The 101repo link was enter some time ago (not just yesterday):

![image](https://cloud.githubusercontent.com/assets/1208815/2902822/4f22b826-d5ea-11e3-8436-65b69feae194.png)

**Comment by burgua** [comment]
Entry is present in pullRepo.json
http://101companies.org/pullRepo.json
