### ISSUE TITLE
treatment of contributors in namespace contribution

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#385]
cc @arkadi-schmidt @avaranovich @tschmorleiz 

Hi Alex and Arkadi,

How are we supposed to refer to developers on those contribution pages?

Here are two contrasting examples:
- http://101companies.org/wiki/Contribution:c with an apparent attempt to refer Contributor:hartenfels, but this does not work.
- http://101companies.org/wiki/Contribution:jdom which talks about Contributor:Ralf Lämmel which is an actual page.

How is it supposed to be?
How do we get the links to the users of the 101wiki v3?
Can you please clarify and get all the contribution data corrected?
If you need any help / discussion, please come forward.

**Comment by rlaemmel** [comment]
As developers (in the metadata section) I suggest in alphabetic order Manfred Jackel, Ralf Lämmel, Matthias Paul

**Comment by burgua** [comment]
is part of https://github.com/101companies/101wiki/issues/323
