### ISSUE TITLE
When in editing mode scrolling down behaves strangely

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#389]
cc @burgua 

cc @tschmorleiz @arkadi-schmidt @mastermaiknemo 

So one has trouble getting to the bottom of a longer page. What happens is shown in the screenshot. That is, one scrolls down out of the page entirely without easily scrolling down through the content of the editing widget. This wasn't like this in the past. Andrei and me can reproduce consistently regardless of resolution.

![image](https://cloud.githubusercontent.com/assets/1208815/3243605/5207133e-f15b-11e3-8a66-8dc87f74835a.png)

**Comment by avaranovich** [comment]
Yes, and regarding of the browser.

**Comment by rlaemmel** [comment]
@mastermaiknemo can't we put this on your shoulder?
This and other issues indicate that the editor has a number of issues.
Perhaps, you could try this?
@tschmorleiz and @avaranovich : is this Ok with you?

**Comment by mminski** [comment]
Hello,
i am working on it. 

Best regards,

Michael

Am 02.07.2014 um 11:38 schrieb Ralf Lämmel notifications@github.com:

**Comment by mminski** [comment]
Seems to be no issue anymore. Scrolling to bottom of longer pages editors doesnt cause trouble in my browser.
