### ISSUE TITLE
mediawiki user id migration to history model of new 101wiki 

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#39]
Edits on the new wiki are already logged according to a history model in mongodb.

https://github.com/101companies/101rails/blob/master/app/controllers/pages_controller.rb

https://github.com/101companies/101rails/blob/master/app/models/history.rb

This means that we can describe functionality to associate pages with user ids.

In the old wiki, the mediawiki user ids are used in a separate logging system.

We need to do two things in the not too distant future:
- Map important mediawiki user ids to github ids.
- Generate some history records from old page edits to represent them with the github ids in the new record model.

**Comment by burgua** [comment]
Is it still legit? @avaranovich @rlaemmel 

About users: after investigation ( https://gist.github.com/burgua/8780b025fd1686f8059a ) was found, that there are less then 20 real users in mediawiki.

**Comment by avaranovich** [comment]
This is correct.

**Comment by burgua** [comment]
Users imported, associated rights granted.
