### ISSUE TITLE
Renaming seems to be troubled

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#391]
cc @avaranovich @martinleinberger 

Just renamed Contributor:Ralf Lämmel to Contributor:rlaemmel

Now I am looking at Contribution:jdom and see this:

![image](https://cloud.githubusercontent.com/assets/1208815/3243755/6c67bed8-f15e-11e3-862e-3c7b3e860bf5.png)

Thus, the renaming has not been pushed through the property.

**Comment by tschmorleiz** [comment]
Fixed during hackathon.
