### ISSUE TITLE
Strange headline for submissions

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#395]
cc @burgua 
cc @tschmorleiz @avaranovich @mastermaiknemo 

Is this generated by the submission process?

![image](https://cloud.githubusercontent.com/assets/1208815/3244824/6ff29cb8-f16c-11e3-917a-be7f80442d9b.png)

I guess it should look like this:

![image](https://cloud.githubusercontent.com/assets/1208815/3244845/a9bc6ab4-f16c-11e3-877c-35d5216221a0.png)

Changed like this over here:

http://101companies.org/wiki/Contribution:MetaC

**Comment by burgua** [comment]
Yes

**Comment by burgua** [comment]
duplicates #394
