### ISSUE TITLE
Strange contrib; remove?

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#398]
cc @burgua 
cc @tschmorleiz @avaranovich anovich @mastermaiknemo 

Who's is this?
No repo link for this one?

![image](https://cloud.githubusercontent.com/assets/1208815/3246293/153fc332-f17a-11e3-8a68-37ca8b0e99de.png)

I removed the page.
If you are aware of more test content, please remove yourselves, as it takes time to guess that something may be test content.

**Comment by burgua** [comment]
Removed test content for contribution process
