### ISSUE TITLE
Make metadata rendering robust under predicate evolution

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#399]
cc @burgua 

cc (fyi) @avaranovich @tschmorleiz 

This appears to be the issue behind #392 

Just talked to A&A, wo confirmed that the handling of metadata links relies on some degree of hardcoded names (presumably for the predicates). 

We need to be very flexible in terms of predicates. So I guess a solution needs to be found such that such hardcoding is either not needed or the set of predicates is retrieved from a central description (such as Andrei's ontology).

Anyway, Alex and Arkadi, please discuss with Andrei, if necessary, or perhaps you find a flexible solution anyway.

**Comment by ghost** [comment]
:cry:

**Comment by avaranovich** [comment]
Here is an example:
http://101companies.org/wiki/Factorial

does not display sameAs property.

The models are here http://worker.101companies.org/data/onto/models/

**Comment by burgua** [comment]
We made it dynamically

https://github.com/101companies/101rails/commit/3d6b6af780259839a4814558676a5075e6b67658

**Comment by burgua** [comment]
So, I see some rendering problem here:

http://take.ms/4oiKE
Triple is found and delivered to client, but not rendered.

**Comment by burgua** [comment]
Works now

**Comment by avaranovich** [comment]
Did I miss something, but http://101companies.org/wiki/Factorial
does not display "sameAs".

http://monosnap.com/image/h4Osb8oWlfN2GSrUtZlnG6bBQPwHre

**Comment by burgua** [comment]
Yes, you are missing smth.
Investigate **all** the sections.

**Comment by avaranovich** [comment]
All sections are rendered OK. And "instanceOf" is displayed anyhow.

**Comment by burgua** [comment]
And you also looked at **Resources** section??

**Comment by avaranovich** [comment]
OK, see it here. Closing.
