### ISSUE TITLE
Scalability issue with github-based versioning

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#401]
cc @arkadi-schmidt 

You just told me that there is a severe scalability issue which prevents you from deploying this feature (as described in MSC thesis).

Please:
- describe the issue in some detail here.
- Also, please refer to the branch with the code.
- Perhaps, reflect on possible lines of attack.

**Comment by burgua** [comment]
## List of Issues

Here will be described issues preventing from deploying GitHub-based versioning.

Branch with first working version of GitHub-based versioning:
https://github.com/101companies/101rails/tree/github-versioning

### Page renaming mechanism

Classical wiki doesn't rewrite content of pages, that has reference to renamed page.
In our case every rename of page triggers rewriting other pages. This mentions, that changing only 1 page, you can actually change another pages.

If actual versioning mechanism is used "renaming" action for restoring pages using versioning (if name was changes), such kind of renaming need to be or made with filesystem (such renaming is not reliable enough), what can lead to situation, that backup content is not the same, as content on the wiki.

On other side, if every rename/update action will also contain any linked pages in versioning, this can lead to situation, that versioning information will be to "heavy".

### Time of execution

Were made mechanism, that writes content of all pages to folder, previously deleting all data in this folder. This approach is not fast enough to be made on the fly. It leads to a delay for every update/rename operation to page.

And in case of frequent changes or work of two or more users on one page, it can also produce git conflict and losing of data.

### Possible Git Conflicts

If enough people are involved in development, that can lead to situation, when someone commits and pushes some changes to repo, what can produce conflicts on server and new data to be backup cause of git conflicts.

**Comment by rlaemmel** [comment]
Closing this one because we will need someone to work on this.
