### ISSUE TITLE
renaming seems to fail (under certain conditions?)

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#403]
cc @tschmorleiz can you help Michael?

Just renamed 

Script:Parsing_and_unparsing_in_Haskell

to 

Script:Unparsing_and_parsing_in_Haskell

It did not change the following markup:

<pre>
Lecture [[Script:Parsing and unparsing in Haskell | Parsing and unparsing]]
</pre>

Must be something special about this markup?

**Comment by rlaemmel** [comment]
Dear @tschmorleiz , can you help @mastermaiknemo to get into this feature area of "renaming".

I think if he tries to investigate this by himself, it may be hard. So please help.

**Comment by mminski** [comment]
Hallo Ralph,

it was just a typo @ 101companies.org/wiki/Script:Unparsing_and_parsing_in_Haskell
It worked like this
[[Script:Unparsing and parsing in Haskell | Parsing and unparsing]]
