### ISSUE TITLE
file rather than fragment reference feature

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#404]
cc @tschmorleiz @avaranovich Perhaps you can help a bit.

I would like to refer to files on wiki pages like this:

```
 * <file url='src/Company/Data.hs'/>
```

Doing this over here:

http://101companies.org/wiki/Contribution:hughesPJ

It sort of works, but:

(i) The relative path is not rendered; instead it is rendered like this:

![image](https://cloud.githubusercontent.com/assets/1208815/3591654/bcd40782-0c66-11e4-9419-67483c6e7ca7.png)

(ii) The file/url syntax is not documented in the editor help; see here:

![image](https://cloud.githubusercontent.com/assets/1208815/3591671/dee1a55a-0c66-11e4-99b5-f47b4cbf0aff.png)

**Comment by rlaemmel** [comment]
@avaranovich do you agree that we would longer paths?

**Comment by avaranovich** [comment]
I suggest we introduce an attribute to be able to keep a "short" path. Rendering a long path in the running wiki text might be harder to read. By default we could render a "long" version. @mastermaiknemo The fragment handling is done here https://github.com/avaranovich/wikicloth/blob/master/lib/wikicloth/extensions/fragment.rb

**Comment by mminski** [comment]
File reference is working as expected.
