### ISSUE TITLE
101wiki/101explorer collaboration broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#405]
Please go here:

http://101companies.org/wiki/Language:Java
- Problem 1: Loading takes long.
- Problem 2: Fragment is not rendered (Error message: "it took too long to render ...")
- Problem 3: Trying to save the page does not terminate.

Another page with the same Problem:

http://101companies.org/wiki/Contribution:haskellStarter

So it probably means that the fact extractor for both Java and Haskell are not working properly or that there is a more generic problem.

**Comment by rlaemmel** [comment]
So the explorer seems to work.
That is, we can get to here:
http://101companies.org/resources/contributions/haskellStarter/src/Main.hs/type/Address?format=html
So somehow the explorer is not used in the right way.
Reassigning to Michael.

**Comment by avaranovich** [comment]
Progress report:

some fragments are back, e.g.
http://101companies.org/wiki/Contribution:haskellVariation

the others still don't work
101companies.org/wiki/Contribution:javaComposition

caching needs to be investigated

**Comment by mminski** [comment]
Hi,

HaskellStarter is working again. If you save a single section the fragments will be rendered correctly but if you edit the whole page the saving leads to errors.
I´ll try to find the bug and fix it for all pages..

**Comment by mminski** [comment]
Hello,

the fragments are rendering again. View : http://101companies.org/wiki/Contribution:haskellStarter

Regards,

Michael

**Comment by rlaemmel** [comment]
Thanks, Michael.
Yes, looks good.
However, I observe a perf issue that we may need to work on.
Filling a new issue accordingly.
Ralf
