### ISSUE TITLE
perf issue with pages with fragments

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#409]
It looks like pages with fragments load successfully but very slow.

Here is an example:

http://101companies.org/wiki/Contribution:javaStatic

Here is another example:

http://101companies.org/wiki/Contribution:haskellStarter

My measurements indicate that it takes about 10 secs.

We use to have much better perf.

I would say that we strive for a upper bound of 2 secs, 1 sec typically.

Obviously, it will not be straightforward to get this perf, but it is important.

**Comment by mminski** [comment]
Performance improved in 2014. Issue closed.
