### ISSUE TITLE
page / fragment not loading

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#410]
Please go here:

http://101companies.org/wiki/Language:Java

The HelloWorld program, which is included per fragment markup, is not rendered.

Instead, some error message is shown.

**Comment by mminski** [comment]
Hello,

the File is loading again. It was a file-tag and not a fragment-tag. If you want to render a code-fragment in the "/Language:" namespace, there is some more implementation needed. But i dont know it is necessary to render Code in this namepace.

Best regards,

Michael
