### ISSUE TITLE
editing not enabled

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#412]
I can edit sections but not the entire page.

See screen shot.

![image](https://cloud.githubusercontent.com/assets/1208815/4157463/f5924d64-347e-11e4-9cc4-d78a3221dbae.png)

**Comment by rlaemmel** [comment]
There is more broken with this paper.

Two times "Details".

![image](https://cloud.githubusercontent.com/assets/1208815/4157550/ef142556-347f-11e4-9423-e0326f28a75f.png)

**Comment by mminski** [comment]
Hello Ralph,

the page works correctly again --> http://101companies.org/wiki/Fold
There was something wrong with the wiki-markup.

Regards,

Michael
