### ISSUE TITLE
file etc. markup does not seem to work

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#44]
I tried to start using it here:

http://beta.101companies.org/wiki/Contribution:haskellSyb

I tried with this markup:

 <file url="haskellSyb/src/Company/Generics.hs"/>

(.... because this is what I understood the current conventions are from what Andrei said on Skype.)

The markup is shown, as is. No file content is shown.

Two things are important with regard to the URL:
- We should support ''relative'' URLs. In the example, it should suffice to say "src/Company/Generics.hs" or "./src/Company/Generics.hs".
- We should allow URLs to other namespaces. So if we were to use an absolute URL, then this should be "/contributions/haskellSyb/src/Company/Generics.hs".

**Comment by rlaemmel** [comment]
Ok, I can provide more details.

The trouble was that I had a space in front of the markup.

When I removed the space, the file would be linked.

It is rendered like this:

BEGIN
1. https://github.com/101companies/101haskell/tree/master/contributions/haskellSyb/src/Company/Generics.hs
END

Why "1."?

How do I get to see the content of the file rather than this link?

(Is there documentation?)

The issue with failing on heading spaces should be fixed.

Also the two other things above.

**Comment by rlaemmel** [comment]
BTW, there is now a somewhat related issue here:
https://github.com/101companies/101worker/issues/47

Also, please not that the file in question was actually moved recently.
I also tried with haskellCabal/src/Company/Total.hs which is discoverable.

**Comment by rlaemmel** [comment]
Just confirming that I was able to see <fragment .../> working. So my issues are about <file .../>.

**Comment by avaranovich** [comment]
@rlaemmel now files are linked OK?
all supported tags are in this example document, which is used for testing https://github.com/avaranovich/wikicloth/blob/master/sample_documents/fragments.wiki
the proper documentation will be added as soon as we finalize this part.

**Comment by rlaemmel** [comment]
Waiting for @martinleinberger to fix some related stuff and for 101worker to make its round before I can say.

**Comment by rlaemmel** [comment]
Andrei, the doc does not suggest that these issues were fixed:
- cover more than just contributions,
- use / for absolute reference,
- support relative references (not starting in /) -- relative to page.
  Can we prioritize this?

**Comment by avaranovich** [comment]
Added context handling.
Example. Suppose we're on the http://101companies.org/wiki/Contribution:haskellSyb

```
<fragment url="src/Company/Total.hs/pattern/total"/> (relative path)
```

is equal to

```
< fragment url="/contributions/haskellSyb/src/Company/Total.hs/pattern/total"/> (absolute path)
```

both are resolved to http://101companies.org/resources/contributions/haskellSyb/src/Company/Total.hs/pattern/total

an update is already deployed to beta.101companies.org
