### ISSUE TITLE
More balanced skip between text and rendered fragments

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#47]
Let's look at this, for example:

http://beta.101companies.org/wiki/Contribution:haskellStarter

There is quite some vertical space within the boxes for fragments, right before the fragment.

There is very little space, though, between the preceding text and the actual box. There needs to be more such space.

Ideally, text and box at least as much separated as the box' content is separated from its top.

**Comment by tschmorleiz** [comment]
Top and bottom margin of syntax-highlighting boxes set slightly higher than padding.
