### ISSUE TITLE
No line wrapping in itemized lists

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#48]
Let's go here:

http://beta.101companies.org/wiki/Contribution:haskellStarter

Than have a look at the Relationships section.

The item is not wrapped.

In fact, it is impossible to see all the text: "In the interest of maintaining a very simple simple beginner's example, the present contribution is about the only contribution which does not commit to packaging, unit testing, and modularization. See Contribution:haskellCabal for packaged and modularized variation with also unit tests added."

**Comment by tb91** [comment]
mhh I tested it and it works fine... I can see the hole text..  so why does it not work on your machine? maybe using mac? ;-P

**Comment by tschmorleiz** [comment]
I can in fact not reproduce the bug. For me (Chrome 26.0.1410.43, Mac OS X 10.8.1) wrapping looks fine.

**Comment by rlaemmel** [comment]
@tschmorleiz, You may have had trouble reproducing it because the content was changed recently.

That is, the "*" was removed in front of the one and only paragraph in "== Relationship ==".

I put the "*" back so that it is an item again.

This brings back the problem.

I am using this: Chrome Version 26.0.1410.43, Mac OS 10.6.8.

Same problem with Firefox 13.0.1.

![item](https://f.cloud.github.com/assets/1208815/320925/dd34995c-997a-11e2-9ed3-e2b203c2df8a.jpg)

**Comment by tschmorleiz** [comment]
Ok, now I was able to reproduce the issue. Should be fixed (Changes will show up after next deployment).
