### ISSUE TITLE
Metadata items need to be sort in some way

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#49]
Let's go here for a test case:

http://beta.101companies.org/wiki/Contribution:haskellStarter

I see these items:

```
 ◀thishttp://101companies.org/property/implementsFeature:Salary total
 ◀thishttp://101companies.org/property/implementsFeature:Salary cut
 ◀thishttp://101companies.org/property/implementsFeature:Serializable companies
 ◀thishttp://101companies.org/property/implementsFeature:Flat companies
 ◀thishttp://101companies.org/property/usesLanguage:Haskell
 ◀thishttp://101companies.org/property/usesLanguage:Haskell 98
 ◀thishttp://101companies.org/property/usesTechnology:GHCi
 ◀thishttp://101companies.org/property/instanceOfTheme:Haskell introduction
 ◀thishttp://101companies.org/property/instanceOfNamespace:Contribution
 ◀thishttp://101companies.org/property/instanceOfTheme:Haskell data
 ◀thishttp://101companies.org/property/developedByContributor:Ralf L-C3-A4mmel
```

For instance, there are two "instanceOf::Theme:..." which should be grouped.

I believe the easiest thing is just to group by the namespace of the object and then sort by the unqualified name. Groups by the namespaces should also be sorted by the namespaces.

Of course, we also need to show again the inverse triples and then grouping and sorting should be on the subject.

**Comment by tschmorleiz** [comment]
Triples in Metadata section now ordered by
1. predicate
2. subject or object (depending which one !== "this")
