### ISSUE TITLE
Escaping problem with source code renderer

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#51]
Please have a look here:

http://beta.101companies.org/wiki/Contribution:haskellStarter

```
 -- Extract the salary from an employee
 totalE :: Employee -&gt; Float
 totalE (_, _, s) = s
```

The signature is not Ok.

**Comment by avaranovich** [comment]
I realized that the source code is escaped somewhere inside discovery service. Have a look here (content property)
http://101companies.org/resources/contributions/haskellSyb/src/Company/Total.hs/pattern/total

So I am reassigning the issue to @martinleinberger

**Comment by martinleinberger** [comment]
Yes, I apply some escaping. This is, for example, necessary when the discovery service should display XML source code and the output format should be HTML. 

Unfortunately, I always escaped the content. I changed this now so that escaping is only applied when the output format is HTML.
