### ISSUE TITLE
Make it easier to add a section (or also remove it)

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#53]
One can of course edit a section and then sneak in markup for a new section, but perhaps something more intuitive could be done.

**Comment by rlaemmel** [comment]
I should add that the "trick" that I describe leads to strange results.

Namely, the new section header is not shown upon saving.

However, if I reload the page past saving, then the new section header appears.

**Comment by rlaemmel** [comment]
There is actually a proper bug:

Suppose I add section "Details" by appending it to "Headline" then this is what gets saved. So the metadata section disappears.

```
  == Headline ==

  A distribution unit for [[Language:Haskell]] 

  == Details ==

  Typically, such packages are set up with [[Technology:Cabal]] and possibly made available via [[Technology:HackageDB]].== Metadata ==
  * [[instanceOf::Vocabulary:Haskell]]
```

I am filing a bug on this matter.

**Comment by tschmorleiz** [comment]
The bug itself is fixed. Will add/remove support for sections soon.

**Comment by tschmorleiz** [comment]
Section adding should be possible. Will add removal soon (plus entire page editing).

**Comment by tschmorleiz** [comment]
Added feature for editing entire pages.
