### ISSUE TITLE
Backlinks in old wiki sort of now working

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#59]
(Sometimes it seems to help just to save the backlinking page another time.)

Go here, for example:

http://101companies.org/wiki/Vocabulary:Haskell

It does not show any backlinks.

There are clearly backlinks as we see on the beta wiki:

http://beta.101companies.org/wiki/Vocabulary:Haskell

**Comment by tschmorleiz** [comment]
Fixed.
