### ISSUE TITLE
Attach shallow sections to Wiki.page object on server

### ISSUE THREAD

**Issue by tschmorleiz** [101companies/101wiki#6]
The client currently has to read the pre-rendered page DOM to retrieve the section names, create sections and attach them to Wiki.page object.
As with page name and page categories these shallow sections (that is, the "content" attribute is not set) should be attached to Wiki.page on the server.

**Comment by avaranovich** [comment]
Added this API
http://localhost:3000/api/pages/101implementation:hadoop/sections

Why don't populate the model on the client? The server bootstrap doesn't help here.
Please check if it's OK for you, then I close the issue.
