### ISSUE TITLE
Save scrumbles section structure

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#61]
Suppose I add section "Details" by appending it to "Headline" then this is what gets saved. So the metadata section disappears.

```
  == Headline ==

  A distribution unit for [[Language:Haskell]] 

  == Details ==

  Typically, such packages are set up with [[Technology:Cabal]] and possibly made available via [[Technology:HackageDB]].== Metadata ==
  * [[instanceOf::Vocabulary:Haskell]]
```

This relates to this issue: https://github.com/101companies/101wiki/issues/53

**Comment by tschmorleiz** [comment]
Fixed. Sections are now checked whether they contain exactly one actual section header.
