### ISSUE TITLE
subject, object in triples on pages must be clickable

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#63]
Backlinks are clickable, but not the subjects, objects (other than "this") in triples.

**Comment by tschmorleiz** [comment]
Should be fixed in next deployment. Code pushed.

**Comment by rlaemmel** [comment]
Links seem to be mis-composed.

I get this:

http://beta.101companies.org/wiki/wiki/Feature:Cut

when clicking the object for the Cut feature on this pager:

http://beta.101companies.org/wiki/Contribution:haskellSyb

**Comment by tschmorleiz** [comment]
Deployed fix.
