### ISSUE TITLE
"Rename" needed

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#64]
It would need to do what the existing 101dev/tools/wikiRefactorer does.

That is, it would need to also rename all references and not just rename the page.

**Comment by rlaemmel** [comment]
Especially with the cache for the new wiki, even just mediawiki or CLI renaming is so complicated that we really need to address this.

**Comment by tschmorleiz** [comment]
Works as the our lovely wikiRefactoring tool does :-). Moves the page (no redirects generated) and fixes all references. When there are many backlinks this actually takes a some seconds (as with the tool). 

Please report any strange behavior or non-fixed references.

**Comment by rlaemmel** [comment]
Oh godness, this is beyond joy.
Wow!
Great!
Ralf
PS: You can count on me to test this shortly.
