### ISSUE TITLE
Some term not handled by book linking service

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#65]
Let's look at this:
http://beta.101companies.org/wiki/Error
No book links are shown.

It is mapped like this:
FREQ,error,Error,
in 101integrate/data/perbook/RWH/metadata/mapping.csv 

What's special about this one?
- It uses FREQ in the mapping.
- It has been added only yesterday evening.

**Comment by tschmorleiz** [comment]
Now showing up due to fresh worker cycle.
