### ISSUE TITLE
github link feature for new wiki

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#68]
I just saw @tschmorleiz fixing the github link feature on the old wiki, but the FP course, for example, will need to use the new wiki. So can we also have the feature for the new wiki? Arguably, we could also link to the discovery service because it provides a whole lot of additional information. So let's discuss.

**Comment by tschmorleiz** [comment]
Created a silly little worker service serving "instances" of an appropriate backbone.js model: http://worker.101companies.org/services/sourceLinks/happstack.jsonp

**Comment by tschmorleiz** [comment]
Added links to GitHub and also the .zip file to the navigation bar. See http://beta.101companies.org/wiki/Contribution:haskellSyb for instance.

**Comment by rlaemmel** [comment]
Looks great.

Perhaps "Code" would be more suggestive than "Source"?

Or is it just me?

@avaranovich ?

**Comment by avaranovich** [comment]
Yes, "Code" is better.

**Comment by tschmorleiz** [comment]
Ok.

**Comment by avaranovich** [comment]
http://101companies.org/wiki/contribution:haskellStarter doesn't have the link

**Comment by tschmorleiz** [comment]
http://101companies.org/wiki/Contribution:haskellStarter does :) Let me make this more robust.

**Comment by tschmorleiz** [comment]
Fixed.

**Comment by rlaemmel** [comment]
Still called "Source".
Should be "Code" as we agreed.
