### ISSUE TITLE
Search feature for the new wiki

### ISSUE THREAD

**Issue by tschmorleiz** [101companies/101wiki#70]
We need a search feature for the new wiki. There could be two options:
- Search based on title
- Search based on content

**Comment by rlaemmel** [comment]
Assigned the search feature to a milestone to express relative urgency.

Perhaps, we could tunnel through the mediawiki search feature as a starting point.

**Comment by rlaemmel** [comment]
This is really important for using the wiki effectively.
So I changed the milestone.

**Comment by rlaemmel** [comment]
Just discussed with @tschmorleiz 
So we would try to use the mediawiki API for this search feature.
Not super high-prio but student experience would definitely benefit from this.

**Comment by tschmorleiz** [comment]
Added a very simple search feature based on the previous discussion.

**Comment by rlaemmel** [comment]
Great. This is good for now. I find the mediawiki approach usually overwhelming for our purposes. Mostly, I would be happy with what you show now. Only, occasionally I would want to see more (along the lines of what mediawiki tries by previewing the pages' text and highlighting hits). Great!
