### ISSUE TITLE
First version of contribution web page

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#71]
I am trying to capture here what I think is the consensus of what the basic page should look like. I **strongly** recommend pushing for a mockup or a basic prototype so that we can incrementally validate and advance our understanding and requirements. Thus, below, a broader vision is described on much more than the "first" version to place everything in the right context.
## Rationale

Generally, the least possible burden should be placed on the user in terms of what needs to be edit / filled in. The contribution process should be sort of a "push button" process. :-) Other than that let's be very incremental and agile about this part. We want the basic functionality up and running now and want to make the right picks as to incrementally grow the full system over the next 2-3 months.
## URL

So let's assume the landing page for the contribution process would be something like 

http://101companies.org/contribute

or anything that works at this point. 

@avaranovich would be the person to know about URLs and deployments.
## Authentication

Before the submitter (contributor) can do anything, she needs to authenticate. The page needs to require github authentication in the same sense as the wiki also requires. Thus, the contribution page needs to help with logging in through github. The implementation of that aspects **must** reuse (and possibly revise, if needed) the infrastructure and the approach chosen by (the new) 101wiki. @avaranovich is the contact again.
## Repo designation

The page needs to help with selecting a github repo. This would be either a repo that is "owned" by the authenticated user or a repo for which that guy is _collaborator_. In the basic version of the web page, the user would simply enter the URL pointing to the repo. (Go for that basic version to be fast.)  In the more advanced version, the use could be offered some selection UI.
## Subdir designation

This is not needed for a first version! We need to be prepared for the case that the contribution is actually not the entire repo, but rather a subdir thereof. Thus, the user must have the opportunity to point to, or better even, to select a subdir. (We can leave this out for the most basic prototype in the beginning.) Over time, multiple contributions could come from one repo.
## Name designation

This is not needed for a first version! By default, we could assume that the name of the repo (or the selected subdir, if such selection happened) would be reused as the proposed name of the contribution. We should allow the user though to override that name.
## Submission for analysis

So upon doing all the designation, as described above, the user essentially says "Submit" (or "Analyze" or something) and the stuff goes to the server where cloning and matching happens and JSON -- that part is already working rudimentarily as the recent demo showed. (Great!)
## Processing results

The returned JSON would contain all kind of information but also specifically some metadata units for "languages" and "technologies" and "concepts"  and "features". (At this point, the data returned by the service only contains infos about languages and technologies, but more stuff is to come and I will file issues accordingly.)

The simple approach is really just to walk the JSON and extract all "languages", "technologies", etc.

More filtering could be needed. This is not needed for a first version! For instance, some files may be tagged to be "ignore"d and hence associated metadata units should not be counted.
## Rendering results

The names of entities obtained by processing/filtering the server response should be presented to the user in listboxes for languages, etc. The stuff should be probably be rendered and grouped etc. as in the metadata section on the wiki. (Do something really simple to start with and we discuss this some more then.)
## Editing results

This is not needed for a first version! The user might disagree on some of these findings and add and remove some languages, etc.
## Designation of a headline

This is not needed for a first version! The user should be able to enter a one-liner headline to summarize the contribution. Help should be provided here by showing some strong examples of existing contributions. The headline should be softly required based on coloring or having the user confirm an empty headline upon final submission. We should though allow the user to continue without headline if she wishes to push through.
## Submission for inclusion

Now the user says "Submit" (or whatever verb/action makes sense) for another time. This will create a TODO record on the server such that some 101gatekeeper has to look into it. (It looks like the record would be written to the mongodb instance by the supporting service.) The record contains all data as for "Submission for analysis" (github user, repo, subdir) and all the edits for languages, technologies, features, and headline.
## UI for guided process

Probably, we should think of a guided, **step-wise** process where the user sees that a small number of steps is to be completed --- just like social networks do for sign-up. Some cool design is appreciated. Usability is very important to us. Please analyze, propose, and push for decision.
## Post-submission process

What has been described up to now is the mere submission process from the point of view of the webpage as the contributor uses it initially. To provide more context and to hint at a whole range of features that will be needed also, here is what happens after "submission for inclusion": 
- The gatekeepers are informed about the TODO record as mentioned above.
- Send "Under review" email to submitter.
- A gatekeeper uses some admin interface to "confirm" the contribution. This will imply several events:
  - Add project to .gitdeps on 101repo.
  - Generate a tweet on 101companies.
  - Create a wiki page from the submission data.
  - Send an email to the submitter.
  - Change the status of the submitter so she can edit the just created wiki page.
- Alternatively, the gatekeeper may "reject" with less implications:
  - Send an email to the submitter.

I guess must of these things would be also be implemented by @arkadi-schmidt and @burgua while @avaranovich and @tschmorleiz and @martinleinberger may be able to help here and there. We are all keen to discuss incremental versions.

**Comment by burgua** [comment]
Entire "Epic" was splitted in

101companies/101wiki#187
101companies/101wiki#188
101companies/101wiki#189
101companies/101wiki#190
101companies/101wiki#191
101companies/101wiki#192
101companies/101wiki#193
101companies/101wiki#194
101companies/101wiki#195
101companies/101wiki#196

**Comment by burgua** [comment]
Closing this epic.
Only 2 not closed tickets exist now:

101companies/101wiki#193
101companies/101wiki#196
