### ISSUE TITLE
new 101wiki down (super-slow)

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#73]
When I edit a new page, "saving" does not disappear.
After 1min or so it times out and the page is not synced.
The content is saved.
Section level editing on the same page, after reload, does not save.

**Comment by avaranovich** [comment]
Added a related (editing) issue https://github.com/101companies/101wiki/issues/74.
Section-level editing should not empty page anymore.

**Comment by avaranovich** [comment]
@rlaemmel please do a new test round to see if the perf issue is still exists. I tweak some bits of config and the application code, should be OK now.

**Comment by rlaemmel** [comment]
I did these tests.
1. Tried to load this page by entering it into the URL bar: http://101companies.org/wiki/Information:Contribute Took approx. 5 secs
2. Waited about 30sec. Then tried to reload the same page. Took approx. 8 secs
3. Waited about 10sec. Then tried to reload the same page. Less than a second. Reloaded a few times and things were fast now.
4.  Tried to load this page by entering it into the URL bar: http://101companies.org/wiki/Information:Explore Less than a second.
5. Waited a minute again. Reload took approx. 5 seconds.

**Comment by avaranovich** [comment]
OK, now page loads reduced to ~  < 1sec.

**Comment by rlaemmel** [comment]
Yes, looks good for now.

**Comment by rlaemmel** [comment]
Just waited 42 secs for these pages:

http://101companies.org/wiki/Contribution:haskellStarter

http://101companies.org/wiki/Namespace:Feature

Not that I think the URLs matter.

Reload is now fast again.

**Comment by rlaemmel** [comment]
Next page I tried:

http://101companies.org/wiki/Stack

Took about a minute.
