### ISSUE TITLE
Section edit sends an empty content to the mediawiki

### ISSUE THREAD

**Issue by avaranovich** [101companies/101wiki#74]
Open the page. Go to the section. Edit section. Save. (Should not be any "saving" popups).
Edit the same section 2nd time. Save. Weird things happen. At some point @rlaemmel managed to empty the page. Another time the content just wasn't saved. (After we refreshed the page -- there was an old section content).

Please test the editing process _very_ carefully  and resolve this issue, as we don't want to kill the content.

**Comment by avaranovich** [comment]
Here is what sent to the server as a result of section edit -> Save

categories: []
content: ""
history: {_id:51668a3542b430acd0000001, created_at:2013-04-11T10:02:29Z, page:contribution:haskellStarter,…}
resources: [{name:PIH, fullName:Programming in Haskell, isLinkable:false, primary:[], secondary:[],…},…]
sections: [,…]
sourceLinks: []
title: "contribution:haskellStarter"
triples: []

Why the content here is an empty string?
Here is what server does

if params.has_key?('content')
      page.update(params[:content])
    else
      content = ""
      sections.each { |s| content += s['content'] }
      page.update(content)
    end

of course it saves an empty content of the page. I will add a temporary check for non-empty content.

**Comment by tschmorleiz** [comment]
Yes, sorry, my fault. That should solve it.

**Comment by avaranovich** [comment]
Why do we still need this "Saving" popup?

**Comment by tschmorleiz** [comment]
Why not? The user should get feedback that saving is actually happening and done.

**Comment by avaranovich** [comment]
Could you please point me to any web site doing this? We discussed this with @rlaemmel and the conclusion is that we don't just want to exersize fancy stuff. I do agree, we could warn the user _in case of error_, but no need to notify that "saving" is happening, because this is obvious by clicking "save" button :-)

**Comment by tschmorleiz** [comment]
This has nothing to do with "fancy stuff". If you don't load a new page (i.e. "something is happening") you have to give the user feedback.

**Comment by avaranovich** [comment]
Please show me any example of "saving" notifications via such pop up. Typically only _errors_ are displayed.

**Comment by tschmorleiz** [comment]
Agreed that we give needed positive feedback by the result of parsing. Removed.
