### ISSUE TITLE
Back links / triples frequently missing

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#76]
Go here, for example:
http://mediawiki.101companies.org/wiki/Namespace:Property
Backlinks should list some actual properties, but there is none.

Let me switch to new wiki:
http://101companies.org/wiki/Namespace:Property
The instanceOf triples are also not shown there.

This happens very often for any kind of pages.
Sometimes, by saving some instance pages, the links would come back.

It is extremely hard to work on the wiki without this basic functionality.

**Comment by rlaemmel** [comment]
One triple is actually there:
▶identifies instanceOf this
The backlink is missing though.
I see whether I can add some instanceOf properties for more properties.

**Comment by rlaemmel** [comment]
Here is another example to help with reproducibility of the missing backlinks issue.

Go here:

http://mediawiki.101companies.org/wiki/Namespace:Information

It does not show Information:Markup.

However that page does "instanceOf" link to Namespace:Information. See here:

http://mediawiki.101companies.org/wiki/Information:Markup

Not even saving again the entire page makes the backling occur.

Amazingly, Namespace:Information does show some backlinks.

**Comment by tschmorleiz** [comment]
Seems the rails implementation of the MediaWiki API does not capture these links. Will have to fix on that level.

**Comment by rlaemmel** [comment]
Reassigning to less urgent Milestone.

Also, the problem is less severe than thought.

That is, ...

http://101companies.org/wiki/Namespace:Property looks good now. I assume we were simply facing a cache problem, as I was still editing a bit on Mediawiki when this happened.

Backlinks on mediawiki pages do continue to be incomplete. As of typing this, http://mediawiki.101companies.org/wiki/Namespace:Information shows much less instances than the non-mediawiki page. 

This is not terribly urgent as we discourage use of mediawiki increasingly.

**Comment by tschmorleiz** [comment]
This seem to be caused by pages that start with "101" pointing IN _or_ OUT of the page. Can we get rid of such pages? Otherwise we would have to work around this, on a low level of semantic mediawiki or s.th.

**Comment by rlaemmel** [comment]
We get rid of those. LET's keep on discussing this.

**Comment by tschmorleiz** [comment]
Are there any left?

**Comment by rlaemmel** [comment]
I think we are good now.
