### ISSUE TITLE
How do we deal with "developedBy" properties on the new wiki?

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#77]
I guess @burgua or @arkadi-schmidt may also be the right persons for this issue.

Anyway, we need to discuss first.

Currently, we assume that contributors have associated 101wiki pages.

Will this continue to be like this?

Should we automatically create these pages during contribution submission?

Should that the contribution web page have the contributor confirm the name of her/him?

**Comment by burgua** [comment]
I would say:

> Will this continue to be like this?
> Yes
> 
> Should we automatically create these pages during contribution submission?
> Yes
> 
> Should that the contribution web page have the contributor confirm the name of her/him?
> No

**Comment by burgua** [comment]
is part of https://github.com/101companies/101wiki/issues/323
