### ISSUE TITLE
Solve prefix legacy

### ISSUE THREAD

**Issue by tschmorleiz** [101companies/101wiki#8]
Currently these prefixes are used in the wiki:

101contributor
101feature
101idea
101internal
101priority
101profile
101status
101term
101view
Contribution
Contributor
Dotnet
Internal
Java
Language
Namespace
Technology
Techology
Theme

We should retire those we don't really use at this point, respectively have found other places to put the content.

**Comment by rlaemmel** [comment]
I am working on this sporadically. This will take some time.
I am going to use this query pattern to find all pages with some prefix:
http://101companies.org/api/api.php?action=query&generator=allpages&gapprefix=101view&format=json

**Comment by rlaemmel** [comment]
We need some tool support and procedure to address this.
Closing this for now, as it cannot be addressed in the intended way.
