### ISSUE TITLE
Subsections are handled strangely

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#81]
Let's go here:

http://101companies.org/wiki/Information:Discover

I am using "=== ... ===" subsections in "Description".

This error message appear upon saving the section:

Validation Error: More than one section header specified

Also, when the section is rendered, then some sort of table of contents appears in the section.

**Comment by rlaemmel** [comment]
Oops, the page was not even saved when these subsections were added.

That's very strange because the subsections are rendered past save.

**Comment by tschmorleiz** [comment]
Should be fixed.
