### ISSUE TITLE
Section-level edit broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#83]
I tried to edit "Illustration" here:

http://101companies.org/wiki/Stack

Clicking "Save" for the first time doesn't do anything.

Clicking it for the second time, starts saving but the "Saving" popup never disappears. I waited like a minute.

I clicked it away and do a reload: the edited content is there.

**Comment by rlaemmel** [comment]
Pressing "Edit" should also make the UI respond immediately.
It is a short second before something happens.

**Comment by tschmorleiz** [comment]
Clicking "Save" when nothing was changed will not save. Will disable the button in that case.

The delay is probably due to slow MediaWiki.

**Comment by tschmorleiz** [comment]
Fixed.
