### ISSUE TITLE
Old and new 101wiki out of sync

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#91]
http://101companies.org/wiki/Course:Lambdas_in_Koblenz

versus

http://mediawiki.101companies.org/wiki/Course:Lambdas_in_Koblenz

The first page lists a MUCH shorter (earlier) description that the second.

**Comment by tschmorleiz** [comment]
I guess this happened during the migration effort or s.th. related. Assigning Andrei.

**Comment by rlaemmel** [comment]
Things are very much out of sync.

http://101companies.org/wiki/Course:Lambdas_in_Koblenz

Shows content that must be days old.

See the mediawiki page for comparison.

**Comment by rlaemmel** [comment]
@avaranovich so how do I make sure that things are in sync?

The new wiki still has a number of issues that make it hard to be used for editing.

**Comment by avaranovich** [comment]
Please pull 101rails project; and run 'make clean-cache' command. The pwd you know. It will clean the cache.

**Comment by avaranovich** [comment]
@rlaemmel Does it work for you? I will close the issue then.

**Comment by rlaemmel** [comment]
Does not work but really needs to urgently.

We are going to confuse the beginner's students beyond repair.

http://101companies.org/wiki/Course:Lambdas_in%20Koblenz

This is very old stuff.

**Comment by rlaemmel** [comment]
It only lists one lecture and how this looked like about a week ago:

<pre>
Introduction
Contributions
Contribution:haskellStarter
Concepts
Stack
Quicksort
</pre>

**Comment by avaranovich** [comment]
Please update the cache cleaning script -- should be fine now.

**Comment by rlaemmel** [comment]
Yes, working now. @tschmorleiz observe the URLs though. Some spaces are rendered as "_"; others as escape space. Let's get this right.

**Comment by avaranovich** [comment]
@tschmorleiz you fixed the escaping, right?

**Comment by tschmorleiz** [comment]
Yes.
