### ISSUE TITLE
http://101companies.org to become reasonable

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#92]
Can we please meet about this and get the page reasonable?

I list a few things that need work:
- What is "Home" when you are on "Home"?
- What is "About" supposed to refer to?
- What is "Blog" supposed to refer to?
- "Contact" seems to be a no-op. Should go to "101companies@gmail.com".
- "Languages", "Technologies", etc. seem to be unconnected.
- What is "Foo", "Bar", "Audi", etc.? (Remove?)
- What is the "Quotes" area about?
- "From the blog": How what that work?
- "Subscribe to [what? sic.] our newsletter"
- How does the "Fan Following" work or is supposed to work?
- "Stay in touch" doesn't work.

**Comment by rlaemmel** [comment]
"We maintain the community knowledge" is not community-oriented.

**Comment by rlaemmel** [comment]
There is "1" overlaid over the tagcloud for the technologies. Where does this "1" come from?

**Comment by rlaemmel** [comment]
There seems to be some image reference somewhere in the page but the image shows as "broken/missing".
Please remove.

**Comment by avaranovich** [comment]
Obviously all mentioned above just blocks which should be filled with proper content and assigned with proper names, etc. Let's meet indeed and fill up all the content we come up with.
