### ISSUE TITLE
Remove maintenance from mediawiki

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#93]
"This page is currently under heavy maintenance. Links and categories will be broken."

Please remove.

**Comment by rlaemmel** [comment]
We need to organize a hackathon to clean up all content so that all maintenance is indeed finished.

Perhaps we could do this in early May.

**Comment by tschmorleiz** [comment]
@avaranovich Was the old wiki moved during the migration effort?

**Comment by avaranovich** [comment]
@tschmorleiz I sent an email with high importance about that :-)
http://mediawiki.101companies.org/

**Comment by tschmorleiz** [comment]
It's gone.
