### ISSUE TITLE
Font / space tuning in rendering section structure

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#94]
This relates to #90 

Let's look at this page for example:

http://101companies.org/wiki/Information:Contribute

"Headline" is super-big. The actual headline is pretty slow. Overall, section headers may be relatively too big. Overall, also, too little content fits on the first screen this way.

**Comment by rlaemmel** [comment]
Do we need indentation for paragraph text? @avaranovich and me think it is perhaps not needed.

**Comment by rlaemmel** [comment]
Perhaps the skip between sections (eg., between Headline and Description) should be less.

**Comment by rlaemmel** [comment]
Perhaps we could even render "Headline" and the actual headline in one line,

**Comment by tschmorleiz** [comment]
Better now in terms of space, font sizes? If so, please close.

**Comment by tschmorleiz** [comment]
Regarding the headline, I would prefer not to come up with an ad-hoc-special-case-solution. Rather I would wait for proper document models; these could be used in the views to indicate whether a given section is a one-liner as opposed to a full-blown section.

**Comment by rlaemmel** [comment]
Yes, it looks better.
Yes, I get your point not to build special knowledge about "Headline" into the implementation.

**Comment by avaranovich** [comment]
@tschmorleiz Do we need indentation for paragraph text? AFAIK, this is not a special case, but a default output from the markup parser. Please handle it on the page in the same way.

**Comment by tschmorleiz** [comment]
Agree. Changed to default indention.
