### ISSUE TITLE
Relative fragment URLs don't seem to work for "concepts"

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#98]
Consider this:

<pre>
<fragment url="/concepts/Stack/Stack.hs"/>
</pre>

This markup occurs here: http://101companies.org/wiki/Stack

We should be able to say this instead:

<pre>
<fragment url="Stack.hs"/>
</pre>

This does not work. Some strange error messages gets rendered in the 101wiki page then.

**Comment by avaranovich** [comment]
Changed http://101companies.org/wiki/Stack to use relative path.
