### ISSUE TITLE
Youtube link missing

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#99]
Please go here:

http://mediawiki.101companies.org/wiki/Information:Download

There is a youtube link listed in the metadata section.

Now go to the new wiki:

http://101companies.org/wiki/Information:Download

No youtube link is rendered.
If I edit the metadata section, then the property is also missing.

Is that a bug because of how the new wiki is not in sync?

Is that instead because we don't know how to render those links?

Anyway, obviously the link must not go lost.

Currently, if I were to edit the page in the new wiki, I would lose information.

**Comment by rlaemmel** [comment]
I did some more testing.
This relates to the infamous "out of sync" issue.
The new wiki seems to hold on old pages rather often.
This is a severe problem.

Reassigning to @avaranovich

**Comment by avaranovich** [comment]
Do I understand correctly, that you changed the data using the _mediawiki_ interface?

The new wiki caches the pages, this is correct. The page is definitely re-cached once it is changed using a new wiki. Once you change the page using mediawiki, cache doesn't know about this change and keeps the old version for some time.

I don't see an obvious solution here, of course I could set some small interval for cache invalidation... The best solution would be to use a new wiki for content creation as well.

**Comment by rlaemmel** [comment]
To answer your question, yes, I edited with mediawiki and I think we still need this.

Also, think of the refactoring tool. It would change many pages.

When you say that it keeps the page "for some time", then please note that this may be several days.

http://101companies.org/wiki/Course:Lambdas_in_Koblenz

I edited this, I believe, 2 days ago and the changes are still not there.

Anyway, even if you applied an interval, this interval could still be problematic.

We need a proper solution here.

Unfortunately, I don't have a simple proposal ready. Perhaps we find a solution via a scrum.

I will not use the new wiki for editing until this is solved because I don't like to think about losing content.

**Comment by avaranovich** [comment]
For refactoring and other needs of changing the data using mediawiki, I can provide a simple script which refreshes the cache. I just did it and the http://101companies.org/wiki/Course:Lambdas_in_Koblenz is up to date.

**Comment by avaranovich** [comment]
BTW, I just realized, that youtube link in the metadata is not related to the "out-of-sync" issue. @tschmorleiz please have a look how you render the metadada and why youtube link is not here. I am reassigning this issue to you while keeping https://github.com/101companies/101wiki/issues/91 for myself.

**Comment by rlaemmel** [comment]
Yes, @avaranovich perhaps I should start using your script then. Does it reset the cache completely? So we really need the cache, right? Some sort of asynchronous check would not be simple, right? Well, let's discuss tomorrow.

**Comment by tschmorleiz** [comment]
Youtube triples are not included by the semantic endpoint. Will fix.

**Comment by rlaemmel** [comment]
Just wondering, what is so special about Youtube? Do we have any issue here with domains that would need to be known?

**Comment by tschmorleiz** [comment]
Instead of whitelisting domains (as we currently do) I will whitelist the prefix for 101companies properties. This approach will be more robust and flexible.

**Comment by tschmorleiz** [comment]
Youtube now found in resource section.
